"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type ViewState = "default" | "loading" | "empty" | "error" | "offline" | "forbidden" | "partial" | "saving" | "not_found" | "sync_conflict" | "insufficient_evidence" | "decision_submitted";
type Region = { type: string; dsId: string; actions?: string[] };
type Screen = { id: string; label: string; route: string; dsId: string; rootDsId: string; layout: string; states: ViewState[]; regions: Region[]; endpoints: string[]; showcase?: string; anchors?: string[] };
type WorkspaceProps = { initialActiveId?: string; storyboardId?: string };

type Task = { id: string; title: string; owner: string; status: string; priority: string; qa: string; trace: string; coverage: number };
type ActionHandler = (event: string, target: string) => void;

const base: ViewState[] = ["default", "loading", "empty", "error", "offline", "forbidden"];
const shellStates: ViewState[] = [...base, "saving", "sync_conflict"];
const focusRing = "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-cyan)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--bg)]";
const panel = "rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface)]";
const inset = "rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)]";
const chip = "rounded-full border border-[var(--border)] px-[var(--space-sm)] py-[var(--space-xs)] text-[0.7rem]";
const stateCopy: Record<ViewState, string> = { default: "Go REST payload rendered.", loading: "Skeleton rows match final layout.", empty: "Specific guidance and retry action.", error: "Inline cause and retry route.", offline: "Read-only cache with queued write notice.", forbidden: "Permission reason and safe return.", partial: "Graph enrichment still completing.", saving: "Write disabled until REST confirmation.", not_found: "Missing entity with parent-list link.", sync_conflict: "Keep local or use server resolution.", insufficient_evidence: "Decision blocked until evidence passes.", decision_submitted: "Audit receipt shown." };
const stateActions: Record<ViewState, string> = { default: "Continue", loading: "Loading", empty: "Clear filters", error: "Retry", offline: "Reconnect", forbidden: "Back to safe route", partial: "Refresh enrichment", saving: "Saving", not_found: "Back to list", sync_conflict: "Resolve conflict", insufficient_evidence: "Add evidence", decision_submitted: "View receipt" };
const allStates: ViewState[] = ["default", "loading", "empty", "error", "offline", "forbidden", "partial", "saving", "not_found", "sync_conflict", "insufficient_evidence", "decision_submitted"];

function r(spec: string): Region { const [type, dsId, actionText] = spec.split("|"); return { type, dsId, actions: actionText?.split(",") }; }
function s(id: string, label: string, route: string, dsId: string, rootDsId: string, layout: string, states: ViewState[], regionSpecs: string[], endpoints: string[], extra: Pick<Screen, "showcase" | "anchors"> = {}): Screen { return { id, label, route, dsId, rootDsId, layout, states, regions: regionSpecs.map(r), endpoints, ...extra }; }
function nextDemoState(current: ViewState, event: string): ViewState {
  if (event === "EVENT_APPROVAL_DECISION") return "decision_submitted";
  if (event === "EVENT_DISCONNECT") return "offline";
  if (event === "EVENT_RECONNECT" || event === "EVENT_RETRY" || event === "EVENT_REFRESH") return "loading";
  if (event === "EVENT_KEEP_LOCAL" || event === "EVENT_USE_SERVER") return "sync_conflict";
  if (event === "EVENT_SAVE_TASK" || event === "EVENT_SAVE_BULK" || event === "EVENT_MOVE_CARD" || event === "EVENT_PI_PLAN_SAVE" || event === "EVENT_CONFIDENCE_VOTE") return "saving";
  if (event === "EVENT_BACK") return "default";
  return current;
}

const screens: Screen[] = [
  s("screen:rtm-dashboard", "RTM Dashboard", "/", "ds:screen:rtm-dashboard-001", "ds:rtm-dashboard:root", "KPI row above coverage heatmap, task progress, graph widget, and gap analysis.", base, ["KpiCards|ds:rtm-dashboard:kpis", "CoverageHeatmap|ds:rtm-dashboard:coverage-heatmap|EVENT_VIEW_TRACE", "TaskProgressPanel|ds:rtm-dashboard:task-progress|EVENT_VIEW_TASK", "KnowledgeGraphWidget|ds:rtm-dashboard:knowledge-graph-widget|EVENT_VIEW_TRACE", "GapAnalysisList|ds:rtm-dashboard:gap-analysis|EVENT_REFRESH"], ["GET /api/coverage", "GET /api/tasks", "GET /api/trace/:id?depth=2", "GET /api/gaps"], { showcase: "#surface-rtm-dashboard" }),
  s("screen:safe-board", "SAFe Board", "/board", "ds:screen:kanban-001", "ds:kanban:root", "Hash-selected board selector, horizontal kanban columns, stats, and RTE escalation badge.", [...base, "saving"], ["BoardSelector|ds:kanban:board-selector|EVENT_HASH_NAVIGATE", "KanbanColumns|ds:kanban:columns|EVENT_MOVE_CARD,EVENT_VIEW_TASK", "BoardStats|ds:kanban:stats", "RteEscalationBadge|ds:kanban:rte-escalation-badge"], ["GET /api/tasks?view=board&board=<id>", "PUT /api/tasks/:id/status", "GET /api/tasks/:id/activity"], { showcase: "/design-system/kanban", anchors: ["sprint", "release", "bug-triage"] }),
  s("screen:task-list", "Task List", "/tasks", "ds:screen:task-list-001", "ds:task-list:root", "Sortable task table with filters, pagination, CSV export, and bulk action bar.", [...base, "saving"], ["TaskFilters|ds:task-list:filters", "TaskTable|ds:task-list:table|EVENT_VIEW_TASK", "BulkActionBar|ds:task-list:bulk-actions|EVENT_SAVE_BULK"], ["GET /api/tasks?format=list", "PUT /api/tasks/bulk"], { showcase: "#surface-task-list" }),
  s("screen:task-detail", "Task Detail", "/tasks/:id", "ds:screen:task-detail-001", "ds:task-detail:root", "Editable task header with Detail, Activity, Graph, Code, and approval-linked tabs.", [...base, "saving", "not_found"], ["EditableFieldGroup|ds:task-detail:editable-fields|EVENT_SAVE_TASK", "TaskTabs|ds:task-detail:tabs|EVENT_HASH_NAVIGATE", "ActivityTimeline|ds:task-detail:activity", "MiniGraphWidget|ds:task-detail:graph-widget|EVENT_VIEW_TRACE"], ["GET /api/tasks/:id", "GET /api/tasks/:id/activity", "GET /api/trace/:id?depth=2", "PUT /api/tasks/:id"], { showcase: "#surface-task-detail", anchors: ["detail", "activity", "graph", "code", "approval"] }),
  s("screen:approval-gates", "Approval Gates", "/approval", "ds:screen:approval-001", "ds:approval:root", "Queue, evidence hub, RTM matrix, heatmap, decision box, and audit receipt split.", [...base, "insufficient_evidence", "decision_submitted"], ["ApprovalQueue|ds:approval:queue", "EvidenceHub|ds:approval:evidence-hub", "RtmMatrix|ds:approval:rtm-matrix", "DecisionControls|ds:approval:decision-controls|EVENT_APPROVAL_DECISION"], ["GET /api/tasks?status=pending-approval", "GET /api/approval/:id/evidence", "GET /api/coverage", "POST /api/approval/:id/decision"], { showcase: "/design-system/approval", anchors: ["panels", "rtm", "heatmap"] }),
  s("screen:doc-viewer", "Doc Viewer", "/docs", "ds:screen:doc-viewer-001", "ds:doc-viewer:root", "Source-type tree beside rendered document panel with Beads badges and coverage markers.", base, ["DocTree|ds:doc-viewer:tree", "RenderedDocument|ds:doc-viewer:content|EVENT_VIEW_TRACE", "SectionCoverageBadges|ds:doc-viewer:section-badges"], ["GET /api/docs?group=source_type", "GET /api/docs/:id", "GET /api/coverage?doc=<id>"], { showcase: "/design-system/doc-viewer" }),
  s("screen:trace-explorer", "Trace Explorer", "/trace/:id", "ds:screen:trace-explorer-001", "ds:trace-explorer:root", "Graph canvas or layered DAG with toolbar, presets, legends, selected node, and detail sidebar.", [...base, "partial"], ["TraceToolbar|ds:trace-explorer:toolbar", "GraphCanvas|ds:trace-explorer:graph-canvas|EVENT_VIEW_TASK,EVENT_VIEW_DOC", "TraversalLayers|ds:trace-explorer:dag-layers", "DetailPanel|ds:trace-explorer:detail-panel"], ["GET /api/trace/:id?depth=full", "GET /api/graph/presets", "GET /api/impact/:section"], { showcase: "/design-system/knowledge-graph", anchors: ["simple", "ecosystem", "sprint", "prd-sections", "plan-elements", "tasks", "commits"] }),
  s("screen:search-explorer", "Search Explorer", "/search", "ds:screen:explorer-001", "ds:search-explorer:root", "Unified query input, hash filters, grouped result list, and detail sidebar drawer fallback.", base, ["SearchInput|ds:search-explorer:input|EVENT_SEARCH", "TypeFilters|ds:search-explorer:type-filters|EVENT_HASH_NAVIGATE", "GroupedResults|ds:search-explorer:results|EVENT_VIEW_TASK,EVENT_VIEW_DOC,EVENT_VIEW_TRACE"], ["GET /api/search?q=<query>&type=<type>"], { showcase: "/design-system/explorer", anchors: ["all", "doc", "commit", "task", "adr", "chat", "spike"] }),
  s("screen:terminal-console", "Terminal Console", "/terminal", "ds:screen:terminal-001", "ds:terminal:root", "Scenario tabs over a 2x2 read-only terminal mosaic for agent, deploy, debug, and CI/CD streams.", base, ["ScenarioTabs|ds:terminal:scenario-tabs|EVENT_HASH_NAVIGATE", "TerminalMosaic|ds:terminal:mosaic", "TerminalLineList|ds:terminal:line-list"], ["GET /api/agents/sessions", "GET /api/ci/runs", "GET /api/tasks/:id/activity", "STREAM /api/log-events?stream=terminal"], { showcase: "/design-system/terminal", anchors: ["agent-console", "deploy", "debug", "ci-cd"] }),
  s("screen:portfolio", "Portfolio", "/portfolio", "ds:screen:portfolio-001", "ds:portfolio:root", "Executive epic table beside Q1/Q2/Q3 2026 roadmap with budget, progress, and forecast.", base, ["PortfolioTable|ds:portfolio:epic-table|EVENT_VIEW_TASK", "Roadmap|ds:portfolio:roadmap"], ["GET /api/portfolio/epics", "GET /api/tasks?issue_type=epic"], { showcase: "/design-system/portfolio" }),
  s("screen:pi-planning", "PI Planning", "/pi-planning", "ds:screen:pi-planning-001", "ds:pi-planning:root", "Strategic sandbox, capacity plan, value scoring, confidence vote, and ROAM board.", [...base, "saving"], ["StrategicSandbox|ds:pi-planning:strategic-sandbox|EVENT_PI_PLAN_SAVE", "BusinessValueScoring|ds:pi-planning:value-scoring", "ConfidenceVote|ds:pi-planning:confidence-vote|EVENT_CONFIDENCE_VOTE", "RoamBoard|ds:pi-planning:roam-board"], ["GET /api/pi/features", "PUT /api/pi/plan", "GET /api/risks?view=roam", "POST /api/pi/confidence-vote"], { showcase: "/design-system/pi-planning" }),
  s("screen:git-graph", "Git Graph", "/git-graph", "ds:screen:git-graph-001", "ds:git-graph:root", "Scenario selector and graph canvas with branches, commits, merge lines, stats, and trace overlay.", base, ["ScenarioSelector|ds:git-graph:scenario-selector|EVENT_HASH_NAVIGATE", "GitGraphCanvas|ds:git-graph:canvas", "CommitDetail|ds:git-graph:commit-detail|EVENT_VIEW_TRACE"], ["GET /api/git/graph?scenario=<id>", "GET /api/trace/:id?include=git"], { showcase: "/design-system/git-graph", anchors: ["gitflow", "multi-agent", "hotfix", "release-train", "monorepo", "beads-prd-trace"] }),
  s("screen:timeline", "Timeline", "/timeline", "ds:screen:timeline-001", "ds:timeline:root", "File lease indicators, activity feed, sprint day timeline, and freshness indicator.", base, ["FileLeasePanel|ds:timeline:file-lease-panel", "ActivityFeed|ds:timeline:activity-feed|EVENT_VIEW_TASK", "SprintDayTimeline|ds:timeline:sprint-day"], ["GET /api/activity", "GET /api/file-leases", "GET /api/tasks/:id/activity"], { showcase: "/design-system/timeline", anchors: ["file-lease", "activity-feed", "sprint-day"] }),
  s("screen:components-catalog", "Components Catalog", "/design-system/components", "ds:screen:components-001", "ds:components-catalog:root", "Catalog of shared primitives with hash section navigation and example slots.", base, ["ComponentSectionNav|ds:components-catalog:section-nav|EVENT_HASH_NAVIGATE", "ComponentExamples|ds:components-catalog:examples"], ["GET /api/design-system/components"], { anchors: ["buttons", "badges-status", "progress", "skeleton", "empty-state", "error-banner"] }),
  s("screen:storyboard-overview", "Storyboard Overview", "/storyboards", "ds:screen:storyboard-001", "ds:storyboard-overview:root", "Journey filter, horizontal use-case flow nodes, guidance panel, and CTA to real screen.", base, ["JourneyFilter|ds:storyboard-overview:filter", "UsecaseFlow|ds:storyboard-overview:flow", "GuidancePanel|ds:storyboard-overview:guidance"], ["GET /api/storyboards"], { showcase: "/design-system/storyboard" }),
  s("screen:storyboard-detail", "Storyboard Detail", "/storyboards/:id", "ds:screen:storyboard-detail-001", "ds:storyboard-detail:root", "Role panel, journey summary, step timeline, related use cases, expected states, and route CTA.", [...base, "not_found"], ["StoryboardRolePanel|ds:storyboard-detail:role-panel", "StepTimeline|ds:storyboard-detail:step-timeline", "RelatedUsecases|ds:storyboard-detail:related-usecases"], ["GET /api/storyboards/:id"], { showcase: "/design-system/storyboard/:id" }),
  s("screen:document-graph-widget", "Document Graph Widget", "embedded", "ds:screen:document-graph-widget-001", "ds:document-graph-widget:root", "Embedded mini graph with filters, zoom controls, node detail panel, and Open Full Page CTA.", base, ["MiniGraphCanvas|ds:document-graph-widget:canvas", "NodeDetailPanel|ds:document-graph-widget:detail-panel|EVENT_VIEW_TRACE"], ["GET /api/trace/:id?depth=2"]),
];

const aliases: Record<string, string> = { "screen:ds-terminal": "screen:terminal-console", "screen:ds-portfolio": "screen:portfolio", "screen:ds-pi-planning": "screen:pi-planning", "screen:ds-git-graph": "screen:git-graph", "screen:ds-kanban": "screen:safe-board", "screen:ds-knowledge-graph": "screen:trace-explorer", "screen:ds-approval": "screen:approval-gates", "screen:ds-timeline": "screen:timeline", "screen:ds-components": "screen:components-catalog", "screen:ds-doc-viewer": "screen:doc-viewer", "screen:ds-explorer": "screen:search-explorer", "screen:ds-beads-traversal": "screen:trace-explorer", "screen:ds-storyboard": "screen:storyboard-overview", "screen:ds-storyboard-detail": "screen:storyboard-detail" };
const surfaceHref: Record<string, string> = { "screen:rtm-dashboard": "#surface-rtm-dashboard", "screen:safe-board": "#surface-safe-board", "screen:task-list": "#surface-task-list", "screen:task-detail": "#surface-task-detail", "screen:trace-explorer": "#surface-trace-explorer", "screen:doc-viewer": "#surface-doc-viewer", "screen:approval-gates": "#surface-approval-gates", "screen:search-explorer": "#surface-search-results" };
const tasks: Task[] = [
  { id: "br-task-742", title: "Bind approval evidence to PRD-04 matrix", owner: "Mina Kovalenko", status: "Review", priority: "P1", qa: "blocked", trace: "br-prd04-s10.3a", coverage: 82 },
  { id: "bd-ds-118", title: "Render trace explorer DAG fallback", owner: "Rafiq Mensah", status: "In progress", priority: "P0", qa: "needs evidence", trace: "br-prd04-s5", coverage: 67 },
  { id: "br-task-681", title: "Queue offline field edits through sync API", owner: "Linnea Park", status: "Done", priority: "P2", qa: "passed", trace: "br-prd04-s7", coverage: 93 },
];
const coverage = ["br-prd04-s1", "br-prd04-s5", "br-prd04-s8", "br-prd04-s10.3a", "br-prd04-s14", "br-prd04-s18a"].map((id, i) => ({ id, pct: [91, 67, 88, 74, 83, 58][i], gaps: [1, 4, 2, 3, 2, 5][i] }));
const board = { Funnel: [tasks[1]], Build: [tasks[2]], Review: [tasks[0]], Done: [{ ...tasks[2], id: "br-task-655", title: "Publish Go REST search response groups" }] };
const people = ["Mina Kovalenko", "Rafiq Mensah", "Linnea Park", "Oskar Iversen"];
const buttonCls = `${chip} ${focusRing} bg-[var(--surface)] text-[var(--text)] hover:bg-[var(--surface-elevated)] active:translate-y-px`;

export default function WebUIPMWorkspacePage({ initialActiveId, storyboardId }: WorkspaceProps = {}) {
  const activeId = initialActiveId ? aliases[initialActiveId] ?? initialActiveId : "screen:rtm-dashboard";
  const activeScreen = screens.find((screen) => screen.id === activeId) ?? screens[0];
  const [query, setQuery] = useState("br-prd04 approval evidence");
  const [status, setStatus] = useState("Review");
  const [priority, setPriority] = useState("P1");
  const [filter, setFilter] = useState("all");
  const [vote, setVote] = useState("4");
  const [decision, setDecision] = useState("request changes");
  const [reason, setReason] = useState("Evidence coverage for br-prd04-s18a is below approval policy.");
  const [eventLog, setEventLog] = useState("EVENT_ROUTE_ENTER -> GET /api/coverage");
  const [demoState, setDemoState] = useState<ViewState>("default");
  const searchRef = useRef<HTMLInputElement>(null);
  const filteredTasks = useMemo(() => filter === "all" ? tasks : tasks.filter((task) => task.status.toLowerCase().includes(filter)), [filter]);
  const handleAction: ActionHandler = (event, target) => { setEventLog(`${event} -> ${target}`); setDemoState((current) => nextDemoState(current, event)); };
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if ((e.ctrlKey && e.key.toLowerCase() === "k") || e.key === "/") { e.preventDefault(); searchRef.current?.focus(); } if (e.key === "Escape") setEventLog("EVENT_CLOSE_OVERLAY -> shell focus restored"); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  const orderedScreens = [activeScreen, ...screens.filter((screen) => screen.id !== activeScreen.id)];

  return (
    <main data-screen-id="screen:global-shell" data-ds-id="ds:screen:webui-pm-workspace-001" data-state={demoState} className="min-h-[100dvh] bg-[var(--bg)] text-[var(--text)]">
      <a href="#active-surface" className={`sr-only focus:not-sr-only focus:fixed focus:left-[var(--space-md)] focus:top-[var(--space-md)] focus:z-10 focus:rounded-[var(--radius)] focus:bg-[var(--surface-elevated)] focus:p-[var(--space-sm)] ${focusRing}`}>Skip to main content</a>
      <section data-ds-id="ds:global-shell:root" className="mx-auto grid min-h-[100dvh] max-w-[1500px] grid-rows-[auto_1fr_auto] border-x border-[var(--border)] bg-[var(--surface)]">
        <header data-ds-id="ds:global-shell:header" className="border-b border-[var(--border)] p-[var(--space-md)] md:p-[var(--space-lg)]">
          <div className="grid gap-[var(--space-md)] lg:grid-cols-[minmax(0,1fr)_minmax(18rem,32rem)_auto] lg:items-end">
            <div><p className="font-mono text-xs uppercase tracking-[0.22em] text-[var(--text-dim)]">PRD-04 WebUI PM Workspace</p><h1 className="mt-[var(--space-xs)] text-3xl font-semibold tracking-tight">Go REST API workspace shell</h1><p className="mt-[var(--space-sm)] max-w-3xl text-sm text-[var(--text-dim)]">Browser UI consumes normalized API payloads only; repository, CI, and graph stores remain backend-owned behind gmind serve endpoints.</p></div>
            <form role="search" aria-label="Global PM workspace search" className="grid gap-[var(--space-sm)]" onSubmit={(e) => { e.preventDefault(); handleAction("EVENT_SEARCH", `GET /api/search?q=${query}&type=all`); }}><label htmlFor="workspace-search" className="text-xs text-[var(--text-dim)]">Global search</label><input ref={searchRef} id="workspace-search" name="q" value={query} onChange={(e) => setQuery(e.target.value)} className={`rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)] px-[var(--space-md)] py-[var(--space-sm)] text-sm text-[var(--text)] ${focusRing}`} /><button className={buttonCls} type="submit">Search via GET /api/search</button></form>
            <aside data-ds-id="ds:global-shell:sync-banner" data-state={demoState === "sync_conflict" ? "sync_conflict" : demoState === "offline" ? "offline" : "default"} role="status" aria-live="polite" className={`${inset} p-[var(--space-sm)] text-xs text-[var(--text-dim)]`}><strong className="text-[var(--text)]">Sync monitor</strong><p><span className="font-mono">State: {demoState.replace(/_/g, " ")}</span> — {eventLog}</p><div className="mt-[var(--space-xs)] flex flex-wrap gap-[var(--space-xs)]"><button onClick={() => handleAction("EVENT_DISCONNECT", "GET /api/health failed; cache read-only")} className={buttonCls}>Simulate offline</button><button onClick={() => handleAction("EVENT_KEEP_LOCAL", "POST /api/sync/conflicts/:id/resolve")} className={buttonCls}>Keep local</button><button onClick={() => handleAction("EVENT_USE_SERVER", "POST /api/sync/conflicts/:id/resolve")} className={buttonCls}>Use server</button></div></aside>
          </div>
        </header>
        <div className="grid min-h-0 md:grid-cols-[16rem_minmax(0,1fr)] xl:grid-cols-[18rem_minmax(0,1fr)]">
          <nav data-ds-id="ds:global-shell:sidebar" aria-label="PM workspace surfaces" className="border-b border-[var(--border)] bg-[var(--surface)] p-[var(--space-md)] md:border-b-0 md:border-r md:p-[var(--space-lg)]"><p className="font-mono text-xs uppercase tracking-[0.18em] text-[var(--text-dim)]">Responsive nav</p><ul className="mt-[var(--space-md)] grid gap-[var(--space-xs)]">{screens.filter((screen) => screen.id !== "screen:document-graph-widget").map((screen) => <li key={screen.id}><a onClick={() => handleAction("EVENT_HASH_NAVIGATE", screen.route)} href={surfaceHref[screen.id] ?? screen.showcase ?? "#active-surface"} className={`block rounded-[var(--radius)] border border-transparent px-[var(--space-sm)] py-[var(--space-xs)] text-sm text-[var(--text)] hover:border-[var(--border)] hover:bg-[var(--bg)] ${focusRing}`} aria-current={screen.id === activeScreen.id ? "page" : undefined}>{screen.label}</a></li>)}</ul></nav>
          <section id="active-surface" data-ds-id="ds:global-shell:active-surface" aria-labelledby="active-surface-title" tabIndex={-1} className="min-w-0 overflow-auto bg-[var(--bg)] p-[var(--space-md)] md:p-[var(--space-lg)]">
            <article className={`${panel} p-[var(--space-md)]`}><p className="font-mono text-xs uppercase tracking-[0.18em] text-[var(--text-dim)]">Active contract surface</p><h2 id="active-surface-title" className="mt-[var(--space-xs)] text-2xl font-semibold">{activeScreen.label}</h2><p className="mt-[var(--space-xs)] text-sm text-[var(--text-dim)]">{activeScreen.layout}</p><label className="mt-[var(--space-sm)] grid max-w-sm gap-1 text-xs text-[var(--text-dim)]">Preview boundary state<select value={demoState} onChange={(e) => setDemoState(e.target.value as ViewState)} className={`${inset} p-2 text-[var(--text)] ${focusRing}`}>{allStates.map((state) => <option key={state}>{state}</option>)}</select></label>{storyboardId ? <p className="mt-[var(--space-xs)] font-mono text-xs text-[var(--text-dim)]">storyboard id: {storyboardId}</p> : null}</article>
            <div className="mt-[var(--space-md)] grid gap-[var(--space-md)]">{orderedScreens.map((screen) => <ScreenShell key={screen.id} screen={screen} featured={screen.id === activeScreen.id} demoState={demoState} onDemoState={setDemoState} onAction={handleAction} state={{ status, setStatus, priority, setPriority, filter, setFilter, filteredTasks, vote, setVote, decision, setDecision, reason, setReason, query, setQuery }} />)}</div>
          </section>
        </div>
        <footer className="border-t border-[var(--border)] bg-[var(--surface)] p-[var(--space-md)] text-xs text-[var(--text-dim)]">Desktop keeps shell sidebar and graph details visible; tablet condenses navigation and moves details to drawers; mobile uses overlay navigation, card-list tables, and simplified graph fallbacks.</footer>
      </section>
    </main>
  );
}

function ScreenShell({ screen, featured, demoState, onDemoState, onAction, state }: { screen: Screen; featured: boolean; demoState: ViewState; onDemoState: (v: ViewState) => void; onAction: ActionHandler; state: any }) {
  const activeState = screen.states.includes(demoState) ? demoState : "default";
  return (
    <section id={surfaceHref[screen.id]?.slice(1)} data-screen-id={screen.id} data-ds-id={screen.dsId} data-state={activeState} className={`${panel} scroll-mt-[var(--space-lg)] p-[var(--space-md)] transition-[opacity,transform] duration-200 ease-out ${featured ? "ring-2 ring-[var(--border-highlight)]" : ""}`} aria-labelledby={`${screen.id}-title`}>
      <header className="grid gap-[var(--space-sm)] border-b border-[var(--border)] pb-[var(--space-md)] lg:grid-cols-[minmax(0,1fr)_auto] lg:items-start"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-[var(--text-dim)]">{screen.route}</p><h3 id={`${screen.id}-title`} className="mt-[var(--space-xs)] text-xl font-semibold">{screen.label}</h3><p className="mt-[var(--space-xs)] text-sm text-[var(--text-dim)]">{screen.layout}</p></div><StateStrip states={screen.states} onSelect={onDemoState} /></header>
      <StatePanel screen={screen} state={activeState} onAction={onAction} />
      <section data-ds-id={screen.rootDsId} aria-label={`${screen.label} regions`} className="mt-[var(--space-md)] grid gap-[var(--space-md)] lg:grid-cols-2 xl:grid-cols-3">{screen.regions.map((region) => <RegionShell key={region.dsId} region={region} onAction={onAction} state={state} />)}</section>
      <aside aria-label={`${screen.label} routing and API contract`} className="mt-[var(--space-md)] grid gap-[var(--space-sm)] lg:grid-cols-2"><section className={`${inset} p-[var(--space-sm)]`}><h4 className="font-mono text-xs uppercase text-[var(--text-dim)]">Anchors</h4><p className="mt-[var(--space-xs)] text-xs text-[var(--text-dim)]">{screen.anchors?.join(" / ") || screen.showcase || "primary route"}</p></section><section className={`${inset} p-[var(--space-sm)]`}><h4 className="font-mono text-xs uppercase text-[var(--text-dim)]">Go REST data flow</h4>{screen.endpoints.map((endpoint) => <p key={endpoint} className="font-mono text-[0.7rem] text-[var(--text)]">{endpoint}</p>)}</section></aside>
    </section>
  );
}

function RegionShell({ region, onAction, state }: { region: Region; onAction: ActionHandler; state: any }) {
  return <article data-ds-id={region.dsId} className={`${inset} min-h-32 p-[var(--space-md)]`}><header className="mb-[var(--space-md)]"><p className="font-mono text-xs uppercase tracking-[0.14em] text-[var(--text-dim)]">{region.type}</p><h4 className="mt-[var(--space-xs)] text-sm font-semibold text-[var(--text)]">{region.dsId}</h4></header><RegionContent region={region} onAction={onAction} state={state} /></article>;
}

function RegionContent({ region, onAction, state }: { region: Region; onAction: ActionHandler; state: any }) {
  const ds = region.dsId;
  if (ds.includes("kpis")) return <MetricGrid items={[["Trace coverage", "81.7%"], ["Open gaps", "17"], ["Approval wait", "6.4h"], ["API freshness", "3.8s"]]} />;
  if (ds.includes("coverage-heatmap") || ds.includes("rtm-matrix")) return <div className="grid gap-2">{coverage.map((c) => <button key={c.id} onClick={() => onAction("EVENT_VIEW_TRACE", `/trace/${c.id}`)} className={`${buttonCls} grid grid-cols-[1fr_auto] items-center text-left`}><span>{c.id}</span><span>{c.pct}% / {c.gaps} gaps</span><span className="col-span-2 h-2 rounded-full bg-[var(--surface-elevated)]"><span className="block h-2 rounded-full bg-[var(--accent-cyan)]" style={{ width: `${c.pct}%` }} /></span></button>)}</div>;
  if (ds.includes("task-progress") || ds.includes("epic-table")) return <TaskTable rows={state.filteredTasks ?? tasks} onAction={onAction} compact={ds.includes("task-progress")} />;
  if (ds.includes("knowledge-graph") || ds.includes("graph-widget") || ds.includes("graph-canvas") || ds.includes("document-graph-widget:canvas")) return <GraphPreview onAction={onAction} compact={!ds.includes("trace-explorer")} />;
  if (ds.includes("gap-analysis")) return <List items={["br-prd04-s18a lacks mobile graph fallback evidence", "approval queue needs reject reason audit fixture", "portfolio budget redaction needs forbidden-state copy"]} action="EVENT_REFRESH" onAction={onAction} />;
  if (ds.includes("board-selector") || ds.includes("scenario-selector") || ds.includes("scenario-tabs") || ds.includes("section-nav") || ds.includes("tabs") || ds.includes("type-filters")) return <Pills items={(region.actions?.[0] === "EVENT_HASH_NAVIGATE" ? ["sprint", "release", "bug-triage", "approval"] : ["all", "doc", "task", "commit"])} event="EVENT_HASH_NAVIGATE" onAction={onAction} />;
  if (ds.includes("kanban:columns")) return <div className="grid gap-2 sm:grid-cols-2">{Object.entries(board).map(([name, rows]) => <section key={name} className={`${inset} p-2`}><h5 className="text-xs font-semibold">{name} <span className="text-[var(--text-dim)]">{rows.length}/3 WIP</span></h5>{rows.map((task) => <button key={task.id} onClick={() => onAction("EVENT_MOVE_CARD", `PUT /api/tasks/${task.id}/status`)} className={`${buttonCls} mt-2 block w-full text-left`}>{task.title}<span className="block font-mono text-[0.65rem] text-[var(--text-dim)]">{task.id} to {task.trace}</span></button>)}</section>)}</div>;
  if (ds.includes("stats")) return <MetricGrid items={[["WIP used", "7/12"], ["Blocked", "3"], ["Flow age", "4.7d"]]} />;
  if (ds.includes("rte")) return <Notice title="RTE escalation" copy="Two P0 trace tasks exceed WIP policy; discussion drawer is API-backed activity context." />;
  if (ds.includes("filters")) return <div className="grid gap-2"><label className="text-xs text-[var(--text-dim)]">Status filter</label><select value={state.filter} onChange={(e) => state.setFilter(e.target.value)} className={`${inset} p-2 ${focusRing}`}><option value="all">All tasks</option><option value="review">Review</option><option value="progress">In progress</option><option value="done">Done</option></select></div>;
  if (ds.includes("task-list:table")) return <TaskTable rows={state.filteredTasks} onAction={onAction} />;
  if (ds.includes("bulk-actions")) return <div className="flex flex-wrap gap-2"><span className={chip}>2 selected</span><button onClick={() => onAction("EVENT_SAVE_BULK", "PUT /api/tasks/bulk")} className={buttonCls}>Bulk set priority P1</button><button className={buttonCls}>Export CSV from /api/tasks</button></div>;
  if (ds.includes("editable-fields")) return <div className="grid gap-3"><Field label="Status" value={state.status} setValue={state.setStatus} options={["In progress", "Review", "Done"]} /><Field label="Priority" value={state.priority} setValue={state.setPriority} options={["P0", "P1", "P2"]} /><button onClick={() => onAction("EVENT_SAVE_TASK", "PUT /api/tasks/br-task-742")} className={buttonCls}>Save task fields</button></div>;
  if (ds.includes("activity") || ds.includes("line-list") || ds.includes("activity-feed")) return <ol className="grid gap-2 text-xs">{["13:42 API event recorded qa_status=blocked", "13:47 Evidence link added to br-prd04-s10.3a", "14:03 reviewer requested graph fallback proof"].map((i) => <li key={i} className="border-l border-[var(--border)] pl-3">{i}</li>)}</ol>;
  if (ds.includes("queue")) return <List items={["br-task-742 approval ready after 3/4 evidence checks", "bd-ds-118 requires graph fallback proof", "br-task-681 approved with audit receipt"]} />;
  if (ds.includes("evidence-hub")) return <MetricGrid items={[["PRD links", "14"], ["Test runs", "7"], ["Screenshots", "23"], ["Policy misses", "1"]]} />;
  if (ds.includes("decision-controls")) return <div className="grid gap-2" data-state={state.reason ? "default" : "insufficient_evidence"}><Field label="Decision" value={state.decision} setValue={state.setDecision} options={["approve", "reject", "request changes"]} /><label htmlFor="approval-reason" className="text-xs text-[var(--text-dim)]">Audit reason</label><textarea id="approval-reason" aria-describedby="approval-gate-help" value={state.reason} onChange={(e) => state.setReason(e.target.value)} className={`${inset} min-h-20 p-2 text-sm ${focusRing}`} /><p id="approval-gate-help" className="text-xs text-[var(--text-dim)]">Approval is disabled until evidence and an audit reason are present; blocked state is labeled in text, not color only.</p><button disabled={!state.reason} aria-disabled={!state.reason} onClick={() => onAction("EVENT_APPROVAL_DECISION", "POST /api/approval/br-task-742/decision")} className={`${buttonCls} disabled:cursor-not-allowed disabled:opacity-60`}>Submit decision</button></div>;
  if (ds.includes("doc-viewer:tree")) return <List items={["PRDs / PRD-04-WebUI-and-PM-Workspace.md", "plans / stage2-component-build", "design / webui-and-pm-workspace"]} />;
  if (ds.includes("doc-viewer:content")) return <article className="prose prose-sm max-w-none text-[var(--text)]"><h5>PRD-04 section br-prd04-s8</h5><p>Route coverage maps dashboard, board, tasks, trace, docs, approval, search, and showcase surfaces to Go REST endpoints.</p><button onClick={() => onAction("EVENT_VIEW_TRACE", "/trace/br-prd04-s8")} className={buttonCls}>Open trace</button></article>;
  if (ds.includes("section-badges")) return <div className="flex flex-wrap gap-2">{coverage.slice(0, 4).map((c) => <span key={c.id} className={chip}>{c.id} {c.pct}%</span>)}</div>;
  if (ds.includes("toolbar")) return <Pills items={["depth full", "DAG", "reverse", "impact"]} event="EVENT_HASH_NAVIGATE" onAction={onAction} />;
  if (ds.includes("dag-layers")) return <List items={["PRD section -> plan element -> task -> commit", "Reverse traversal shows approval evidence dependencies", "Partial enrichment badge covers delayed GitHub/FastCode aggregation"]} />;
  if (ds.includes("detail-panel") || ds.includes("commit-detail")) return <Notice title="Selected node" copy="br-prd04-s8 links 18 route surfaces, 21 actions, and acceptance assertion ac:route-coverage." action="EVENT_VIEW_TRACE" onAction={onAction} />;
  if (ds.includes("search-explorer:input")) return <div className="grid gap-2"><input value={state.query} onChange={(e) => state.setQuery(e.target.value)} className={`${inset} p-2 ${focusRing}`} /><button onClick={() => onAction("EVENT_SEARCH", `GET /api/search?q=${state.query}&type=all`)} className={buttonCls}>Run query</button></div>;
  if (ds.includes("results")) return <List items={["Task br-task-742: approval evidence binding", "Doc br-prd04-s8: route map", "Trace br-prd04-s10.3a: gate policy"]} action="EVENT_VIEW_TRACE" onAction={onAction} />;
  if (ds.includes("mosaic")) return <div className="grid gap-2 sm:grid-cols-2">{["agent sessions", "deploy stream", "debug events", "CI checks"].map((name) => <pre key={name} className={`${inset} overflow-auto p-2 text-[0.65rem] text-[var(--text-dim)]`}>{`GET /api/${name.replaceAll(" ", "-")}\nread-only browser stream\nlast event: policy accepted`}</pre>)}</div>;
  if (ds.includes("strategic-sandbox")) return <List items={["Trace Explorer mobile fallback", "Approval audit receipts", "Offline conflict recovery"]} action="EVENT_PI_PLAN_SAVE" onAction={onAction} />;
  if (ds.includes("value-scoring")) return <MetricGrid items={[["BV", "17"], ["Risk", "6"], ["Capacity", "31.5d"], ["WSJF", "8.4"]]} />;
  if (ds.includes("confidence-vote")) return <div className="grid gap-2"><Field label="Confidence vote" value={state.vote} setValue={state.setVote} options={["1", "2", "3", "4", "5"]} /><button onClick={() => onAction("EVENT_CONFIDENCE_VOTE", "POST /api/pi/confidence-vote")} className={buttonCls}>Submit vote</button></div>;
  if (ds.includes("roam-board")) return <Pills items={["Resolved", "Owned", "Accepted", "Mitigated", "Unassigned"]} event="EVENT_HASH_NAVIGATE" onAction={onAction} />;
  if (ds.includes("roadmap")) return <List items={["Q1 2026: route parity and API cache", "Q2 2026: approval policy automation", "Q3 2026: portfolio forecasting and graph impact"]} />;
  if (ds.includes("git-graph:canvas")) return <GraphPreview onAction={onAction} compact />;
  if (ds.includes("file-lease")) return <List items={["PRD-04 locked by Mina Kovalenko, expires in 18m", "page.tsx lease held by Stage 2 builder", "component-map.json read-only generated artifact"]} />;
  if (ds.includes("sprint-day")) return <List items={["09:17 route data hydrated", "11:26 board WIP policy checked", "15:48 approval decision window opens"]} />;
  if (ds.includes("examples")) return <MetricGrid items={[["Buttons", "active"], ["Badges", "AA labels"], ["Skeleton", "matched"], ["Error", "retry"]]} />;
  if (ds.includes("storyboard-overview:filter")) return <Pills items={["PM", "RTE", "Developer", "Approver"]} event="EVENT_HASH_NAVIGATE" onAction={onAction} />;
  if (ds.includes("storyboard-overview:flow") || ds.includes("step-timeline")) return <List items={["Route enter -> loading_to_default", "Action event -> Go REST endpoint", "Success signal -> screen state and trace link"]} action="EVENT_VIEW_TASK" onAction={onAction} />;
  if (ds.includes("guidance") || ds.includes("role-panel") || ds.includes("related-usecases")) return <Notice title="Storyboard guidance" copy="Mechanism, action, considerations, and investigating notes point to real workspace routes." />;
  return <Notice title={region.type} copy={`${region.actions?.join(", ") || "Read-only"} region is bound to normalized Go REST data with accessible labels.`} />;
}

function StatePanel({ screen, state, onAction }: { screen: Screen; state: ViewState; onAction: ActionHandler }) {
  if (state === "default") return null;
  if (state === "loading") return <div data-state="loading" aria-busy="true" className={`${inset} mt-[var(--space-md)] grid gap-2 p-[var(--space-md)]`}><strong>Loading {screen.label}</strong><Skeleton /><span className="text-xs text-[var(--text-dim)]">Matching final {screen.regions.length}-region layout while GET route data completes.</span></div>;
  const endpoint = screen.endpoints[0] || "GET /api/health";
  const copy: Record<ViewState, string> = { ...stateCopy, empty: `No ${screen.label.toLowerCase()} data matched current filters. Clear filters or refresh ${endpoint}.`, error: `${endpoint} returned an API error. Retry keeps browser inside Go REST recovery.`, offline: "Read-only cached data is visible. Eligible writes are queued until POST /api/sync/rehydrate succeeds.", forbidden: "Your role cannot view this dataset. Sensitive fields stay hidden and you can return to the shell.", partial: "Graph uses cached nodes while backend enrichment for GitHub or FastCode is still pending.", saving: "Controls are disabled during the PUT/POST request and roll back if policy rejects the update.", not_found: "The requested entity was not found. Use the parent list rather than guessing a direct store path.", sync_conflict: "Queued local edit conflicts with server data. Choose one version and preserve the audit trail.", insufficient_evidence: "Approval is blocked because required RTM evidence and coverage thresholds are incomplete.", decision_submitted: "Decision submitted; the audit receipt and activity event are available through the API." };
  return <aside data-state={state} role="status" aria-live="polite" className={`${inset} mt-[var(--space-md)] grid gap-2 p-[var(--space-md)] text-sm`}><strong className="capitalize">{state.replace(/_/g, " ")}: {stateCopy[state]}</strong><p className="text-[var(--text-dim)]">{copy[state]}</p><button disabled={state === "saving" || state === "decision_submitted"} aria-disabled={state === "saving" || state === "decision_submitted"} onClick={() => onAction(state === "forbidden" || state === "not_found" ? "EVENT_BACK" : state === "sync_conflict" ? "EVENT_KEEP_LOCAL" : state === "offline" ? "EVENT_RECONNECT" : state === "insufficient_evidence" ? "EVENT_VIEW_TRACE" : "EVENT_REFRESH", endpoint)} className={`${buttonCls} disabled:cursor-not-allowed disabled:opacity-60`}>{stateActions[state]}</button></aside>;
}
function Skeleton() { return <div className="grid gap-2" aria-hidden="true"><span className="h-3 rounded-[var(--radius)] bg-[var(--surface-elevated)] opacity-70" /><span className="h-16 rounded-[var(--radius)] bg-[var(--surface-elevated)] opacity-60" /><span className="h-3 w-2/3 rounded-[var(--radius)] bg-[var(--surface-elevated)] opacity-50" /></div>; }
function MetricGrid({ items }: { items: string[][] }) { return <dl className="grid gap-2 sm:grid-cols-2">{items.map(([k, v]) => <div key={k} className={`${inset} p-2`}><dt className="text-[0.68rem] uppercase tracking-[0.12em] text-[var(--text-dim)]">{k}</dt><dd className="font-mono text-lg text-[var(--text)]">{v}</dd></div>)}</dl>; }
function Pills({ items, event, onAction }: { items: string[]; event: string; onAction: ActionHandler }) { return <div className="flex flex-wrap gap-2">{items.map((item) => <button key={item} onClick={() => onAction(event, `#${item}`)} className={buttonCls}>{item}</button>)}</div>; }
function List({ items, action, onAction }: { items: string[]; action?: string; onAction?: ActionHandler }) { return <ul className="grid gap-2 text-xs">{items.map((item) => <li key={item} className={`${inset} p-2`}>{action && onAction ? <button onClick={() => onAction(action, item)} className={`text-left underline-offset-4 hover:underline ${focusRing}`}>{item}</button> : item}</li>)}</ul>; }
function Notice({ title, copy, action, onAction }: { title: string; copy: string; action?: string; onAction?: ActionHandler }) { return <div className="grid gap-2 text-xs"><strong>{title}</strong><p className="text-[var(--text-dim)]">{copy}</p>{action && onAction ? <button onClick={() => onAction(action, title)} className={buttonCls}>Open trace context</button> : null}</div>; }
function Field({ label, value, setValue, options }: { label: string; value: string; setValue: (v: string) => void; options: string[] }) { return <label className="grid gap-1 text-xs text-[var(--text-dim)]">{label}<select value={value} onChange={(e) => setValue(e.target.value)} className={`${inset} p-2 text-[var(--text)] ${focusRing}`}>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function TaskTable({ rows, onAction, compact }: { rows: Task[]; onAction: ActionHandler; compact?: boolean }) { return <div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr className="text-[var(--text-dim)]"><th>Task</th><th>Status</th>{!compact ? <th>Owner</th> : null}<th>Trace</th></tr></thead><tbody>{rows.map((task) => <tr key={task.id} className="border-t border-[var(--border)]"><td><button onClick={() => onAction("EVENT_VIEW_TASK", `/tasks/${task.id}`)} className={`py-2 text-left underline-offset-4 hover:underline ${focusRing}`}>{task.title}</button><span className="block font-mono text-[0.65rem] text-[var(--text-dim)]">{task.id}</span></td><td>{task.status} / {task.qa}</td>{!compact ? <td>{task.owner}</td> : null}<td>{task.trace}</td></tr>)}</tbody></table></div>; }
function GraphPreview({ onAction, compact }: { onAction: ActionHandler; compact?: boolean }) { const nodes = ["br-prd04-s8", "br-plan-stage2", "bd-ds-118", "br-task-742"]; return <div className="grid gap-2"><div className={`grid ${compact ? "grid-cols-2" : "grid-cols-4"} gap-2`}>{nodes.map((node, i) => <button key={node} onClick={() => onAction(i > 1 ? "EVENT_VIEW_TASK" : "EVENT_VIEW_DOC", `/trace/${node}`)} className={`${buttonCls} min-h-16 text-left`}>{node}<span className="block text-[var(--text-dim)]">{i === 0 ? "PRD" : i === 1 ? "Plan" : "Task"}</span></button>)}</div><p className="text-xs text-[var(--text-dim)]">Edges and enrichment arrive through GET /api/trace/:id only.</p></div>; }
function StateStrip({ states, onSelect }: { states: ViewState[]; onSelect: (v: ViewState) => void }) { return <ul className="flex max-w-md flex-wrap gap-[var(--space-xs)]" aria-label="Declared boundary states">{states.map((state) => <li key={state} data-state={state}><button type="button" onClick={() => onSelect(state)} title={stateCopy[state]} aria-label={`Preview ${state.replace(/_/g, " ")} state: ${stateCopy[state]}`} className={`rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)] px-[var(--space-sm)] py-[var(--space-xs)] font-mono text-[0.65rem] uppercase tracking-[0.12em] text-[var(--text-dim)] ${focusRing}`}>{state.replace(/_/g, " ")}</button></li>)}</ul>; }

export { shellStates };
