import type { ReactNode } from "react";

const focus = "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-cyan)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--bg)]";
const muted = "text-[var(--text-dim)]";
const row = "border-b border-[var(--border)] last:border-b-0";

type StatePanelKind = "loading" | "empty" | "error" | "offline" | "forbidden" | "saving" | "not_found" | "partial" | "insufficient_evidence" | "decision_submitted" | "view_drilldown" | "view_trace" | "sync_conflict";

type Tone = "neutral" | "info" | "warn" | "danger";
const stateCopy: Record<StatePanelKind, { title: string; body: string; action: string; label: string; tone: Tone; live: "status" | "alert" }> = {
  loading: { title: "Loading workspace data", body: "Skeleton rows reserve final dimensions while the browser waits on the Go REST API.", action: "EVENT_REFRESH", label: "Refresh from API", tone: "neutral", live: "status" },
  empty: { title: "No records returned", body: "Create or link a plan, task, document, or trace record through the API-backed workspace flow.", action: "EVENT_OPEN_CREATE_PLAN", label: "Create plan", tone: "info", live: "status" },
  error: { title: "API request failed", body: "Repository, database, shell, git, and CI calls remain behind the Go REST boundary. Retry the safe endpoint.", action: "EVENT_REFRESH", label: "Retry request", tone: "danger", live: "alert" },
  offline: { title: "Offline read-only mode", body: "Cached details remain visible. Edits wait until the API reconnects and confirms the server version.", action: "EVENT_RECONNECT", label: "Reconnect", tone: "warn", live: "status" },
  forbidden: { title: "Permission required", body: "This route needs a PM, RTE, or approver capability. Ask an administrator to update role grants server-side.", action: "EVENT_BACK", label: "Go back", tone: "danger", live: "alert" },
  saving: { title: "Saving draft through API", body: "Changes are staged for PUT through the Go REST endpoint; no browser-side file or database access occurs.", action: "EVENT_FIELD_EDIT", label: "Review draft", tone: "info", live: "status" },
  not_found: { title: "Requested record was not found", body: "The task, storyboard, or trace ID may have moved. Return to the API list and choose an available result.", action: "EVENT_BACK", label: "Back to list", tone: "warn", live: "alert" },
  partial: { title: "Partial trace loaded", body: "The graph reached a depth cap or stale node. Continue with visible evidence or request focused trace refresh.", action: "EVENT_VIEW_TRACE", label: "Refresh trace", tone: "warn", live: "status" },
  insufficient_evidence: { title: "Approval evidence incomplete", body: "Attach test results, PRD trace, and decision notes before approving or rejecting through the approval endpoint.", action: "EVENT_APPROVAL_DECISION", label: "Review evidence", tone: "warn", live: "alert" },
  decision_submitted: { title: "Decision submitted", body: "The approval decision is queued as an auditable REST mutation with PM notes and beads trace links.", action: "EVENT_VIEW_TRACE", label: "View audit trace", tone: "info", live: "status" },
  view_drilldown: { title: "Drill-down opened", body: "Dashboard focus moved to the gap and task evidence behind the selected coverage panel.", action: "EVENT_VIEW_TASK", label: "Open task evidence", tone: "info", live: "status" },
  view_trace: { title: "Trace view opened", body: "The dashboard is showing the PRD-to-task-to-CI trace path requested from the storyboard action.", action: "EVENT_VIEW_TRACE", label: "Open trace explorer", tone: "info", live: "status" },
  sync_conflict: { title: "Server version changed", body: "Review the newer API version before resubmitting local edits.", action: "EVENT_REFRESH", label: "Compare versions", tone: "warn", live: "alert" },
};
const toneClass: Record<Tone, string> = { neutral: "border-[var(--border)]", info: "border-[var(--accent-cyan-dim)]", warn: "border-[var(--accent-amber-dim)]", danger: "border-[var(--accent-rose-dim)]" };

type IconName = "status" | "loading" | "empty" | "error" | "offline" | "forbidden" | "saving" | "partial" | "approve" | "reject" | "changes" | "trace" | "docs" | "task" | "search" | "move" | "filter" | "api";
const iconPaths: Record<IconName, ReactNode> = {
  status: <><circle cx="12" cy="12" r="8" /><path d="m8.5 12 2.5 2.5L16 9" /></>, loading: <><path d="M12 4v4M12 16v4M4 12h4M16 12h4" /><path d="m6.3 6.3 2.8 2.8M14.9 14.9l2.8 2.8" /></>, empty: <><path d="M5 6h14v12H5z" /><path d="M9 10h6" /></>, error: <><path d="M12 4 3 20h18z" /><path d="M12 9v4M12 17h.01" /></>, offline: <><circle cx="12" cy="12" r="8" /><path d="M8 8l8 8M16 8l-8 8" /></>, forbidden: <><circle cx="12" cy="12" r="8" /><path d="M8 16 16 8" /></>, saving: <><path d="M5 4h11l3 3v13H5z" /><path d="M8 4v6h8M8 17h8" /></>, partial: <><path d="M4 12h16" /><path d="M4 12a8 8 0 0 1 8-8" /><path d="M12 20a8 8 0 0 0 8-8" /></>, approve: <path d="m4 12 5 5L20 6" />, reject: <path d="M6 6l12 12M18 6 6 18" />, changes: <><path d="M4 7h10M4 12h16M4 17h10" /><path d="m16 5 3 2-3 2M16 15l3 2-3 2" /></>, trace: <><circle cx="5" cy="12" r="2" /><circle cx="12" cy="6" r="2" /><circle cx="19" cy="12" r="2" /><path d="m7 11 3.5-3M13.5 7 17 11" /></>, docs: <><path d="M6 3h9l3 3v15H6z" /><path d="M9 12h6M9 16h6" /></>, task: <><path d="M8 7h12M8 12h12M8 17h12" /><path d="m3.5 12 1 1 2-2" /></>, search: <><circle cx="11" cy="11" r="6" /><path d="m16 16 4 4" /></>, move: <><path d="M5 12h14" /><path d="m15 8 4 4-4 4" /></>, filter: <><path d="M4 6h16M7 12h10M10 18h4" /></>, api: <><path d="M7 7h10v10H7z" /><path d="M3 10h4M3 14h4M17 10h4M17 14h4" /></>,
};
function Icon({ name, className = "h-4 w-4" }: { name: IconName; className?: string }) { return <svg aria-hidden="true" viewBox="0 0 24 24" className={`${className} shrink-0`} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{iconPaths[name]}</svg>; }
function iconForState(state: StatePanelKind): IconName { if (state === "loading") return "loading"; if (state === "empty") return "empty"; if (state === "error") return "error"; if (state === "offline") return "offline"; if (state === "forbidden") return "forbidden"; if (state === "saving") return "saving"; if (state === "partial") return "partial"; return "status"; }


const kpis = [
  ["PRD coverage", "87.4%", "+6.8 pts", "GET /api/coverage"],
  ["Tasks done", "142", "37 in review", "GET /api/tasks"],
  ["Open gaps", "11", "4 missing CI evidence", "GET /api/gaps"],
  ["Trace depth", "5 hops", "br-prd04-s5 to CI", "GET /api/trace/:id?depth=2"],
];
const coverage = [
  ["br-prd04-s2", "Traceability Pyramid", "heatmap-cell--100", "14/14", "#surface-docs"],
  ["br-prd04-s5", "HITL approval gate", "heatmap-cell--75", "9/11", "#surface-approval"],
  ["br-prd04-s8", "Portfolio planning", "heatmap-cell--75", "12/15", "#surface-board"],
  ["br-prd04-s11", "Document graph", "heatmap-cell--50", "7/12", "#surface-trace"],
  ["br-prd04-s14", "CI status boundary", "heatmap-cell--25", "3/9", "#surface-task-detail"],
];
const tasks = [
  ["bd-approval-178", "Reject path coverage", "Nadia Ro", "In Review", "High", "br-prd04-s5"],
  ["bd-docs-214", "Markdown beads backlinks", "Owen Kaito", "Ready", "Medium", "br-prd04-s11"],
  ["bd-trace-089", "Impact graph depth cap", "Priya Nadir", "Blocked", "High", "br-prd04-s2"],
  ["bd-api-332", "Go REST adapter proof", "Tomas Ivers", "Done", "Low", "br-prd04-s14"],
];
const lanes = [
  ["Ready", "bd-docs-214", "Markdown beads backlinks", "Owen Kaito", "5 evidence items"],
  ["In Review", "bd-approval-178", "Reject path coverage", "Nadia Ro", "7 evidence items"],
  ["Blocked", "bd-trace-089", "Impact graph depth cap", "Priya Nadir", "needs API fixture"],
];
const docs = ["PRD-04 WebUI and PM Workspace", "Plan: Approval Gate", "Spike: Beads Knowledge Graph", "QA: Stage 2 Evidence"];
const graphNodes = ["PRD", "Plan", "Task", "Code", "CI"];
const activity = ["Mira linked br-prd04-s5 to bd-approval-178", "Go API adapter returned coverage delta 87.4%", "QA attached playwright trace evidence", "Reviewer requested CI boundary note"];
const searchResults = [
  ["Task", "bd-approval-178", "Reject path coverage for approval gate", "EVENT_VIEW_TASK", "#surface-task-detail"],
  ["Doc", "br-prd04-s5", "HITL approval gate section", "EVENT_VIEW_DOC", "#surface-docs"],
  ["Trace", "trace:approval-gate", "PRD to CI run gmind-webui-2841", "EVENT_VIEW_TRACE", "#surface-trace"],
];

export function WorkspaceStatePanel({ state, compact = false }: { state: StatePanelKind; compact?: boolean }) {
  const copy = stateCopy[state];
  const liveProps = copy.live === "alert" ? { role: "alert" } : { role: "status", "aria-live": "polite" as const };
  return <aside data-state={state} aria-label={`${copy.title} state recovery`} className={`rounded-[var(--radius)] border ${toneClass[copy.tone]} bg-[var(--bg)] p-[var(--space-sm)]`} {...liveProps}>{state === "loading" ? <SkeletonRows /> : null}<p className="inline-flex items-center gap-[var(--space-xs)] font-mono text-xs uppercase tracking-[0.14em] text-[var(--text-dim)]"><Icon name={iconForState(state)} />{state.replaceAll("_", " ")}</p><h3 className="mt-[var(--space-xs)] font-semibold">{copy.title}</h3><p className={`mt-[var(--space-xs)] text-sm ${muted}`}>{copy.body}</p><a href={`#${copy.action.toLowerCase().replaceAll("_", "-")}`} data-action={copy.action} className={`mt-[var(--space-sm)] inline-flex ${compact ? "btn-sm" : ""} btn-secondary ${focus}`}><Icon name={iconForState(state)} />{copy.label}</a></aside>;
}
function SkeletonRows() { return <div className="skeleton-group" aria-hidden="true"><div className="skeleton skeleton--text-full" /><div className="skeleton skeleton--text-short" /><div className="skeleton skeleton--card" /></div>; }
function Shell({ dsId, children, state = "default", label }: { dsId: string; children: ReactNode; state?: string; label?: string }) { return <article data-ds-id={dsId} data-state={state} aria-label={label} className="rounded-[var(--radius)] border border-[var(--border)] bg-[var(--surface)] p-[var(--space-sm)]">{children}</article>; }
function ApiLabel({ children }: { children: ReactNode }) { return <code className="rounded-[var(--radius)] bg-[var(--bg)] px-[var(--space-xs)] py-[2px] font-mono text-[0.68rem] text-[var(--text-dim)]">{children}</code>; }
function Status({ value }: { value: string }) { return <span className={`badge inline-flex items-center gap-[var(--space-xs)] ${value === "Blocked" || value === "High" ? "badge-rose" : value === "In Review" || value === "Medium" ? "badge-amber" : "badge-teal"}`}><Icon name={value === "Blocked" || value === "High" ? "error" : value === "In Review" || value === "Medium" ? "partial" : "status"} className="h-3 w-3" />{value}</span>; }

export function WorkspaceComponent({ dsId }: { dsId: string }) {
  const map: Record<string, ReactNode> = {
    "ds:rtm-dashboard:kpis": <Kpis />, "ds:heatmap:rtm": <CoverageHeatmap />, "ds:rtm-dashboard:coverage-heatmap": <CoverageHeatmap />, "ds:chart:progress": <TaskProgress />, "ds:rtm-dashboard:task-progress": <TaskProgress />, "ds:graph:mini": <MiniGraph dsId={dsId} />, "ds:rtm-dashboard:knowledge-graph-widget": <MiniGraph dsId="ds:rtm-dashboard:knowledge-graph-widget" />, "ds:list:gaps": <GapList />, "ds:rtm-dashboard:gap-analysis": <GapList />,
    "ds:kanban:columns": <KanbanColumns />, "ds:kanban:stats": <KanbanStats />, "ds:kanban:board-selector": <BoardSelector />, "ds:kanban:rte-escalation-badge": <EscalationBadge />,
    "ds:task-list:filters": <TaskFilters />, "ds:task-list:table": <TaskTable />, "ds:task-list:bulk-actions": <BulkActions />,
    "ds:task-detail:editable-fields": <TaskDetailFields />, "ds:task-detail:tabs": <TaskTabs />, "ds:task-detail:activity": <ActivityFeed />, "ds:task-detail:graph-widget": <MiniGraph dsId="ds:task-detail:graph-widget" />,
    "ds:approval:queue": <ApprovalQueue />, "ds:approval:evidence-hub": <EvidenceHub />, "ds:approval:rtm-matrix": <RtmMatrix />, "ds:approval:decision-controls": <DecisionBox />,
    "ds:trace-explorer:toolbar": <TraceToolbar />, "ds:trace-explorer:graph-canvas": <TraceGraph />, "ds:trace-explorer:dag-layers": <DagLayers />, "ds:trace-explorer:detail-panel": <NodeDetail />,
    "ds:doc-viewer:tree": <DocTree />, "ds:doc-viewer:content": <MarkdownViewer />, "ds:doc-viewer:section-badges": <SectionBadges />,
    "ds:search-explorer:input": <SearchInput />, "ds:search-explorer:type-filters": <TypeFilters />, "ds:search-explorer:results": <SearchResults />,
  };
  return <>{map[dsId] ?? <Fallback dsId={dsId} />}</>;
}

function Kpis() { return <Shell dsId="ds:rtm-dashboard:kpis" label="Coverage KPIs"><div className="grid gap-[var(--space-sm)] sm:grid-cols-2 lg:grid-cols-4">{kpis.map(([label, value, delta, endpoint]) => <div key={label} className="border-l border-[var(--border-highlight)] pl-[var(--space-sm)]"><p className="font-mono text-xs uppercase tracking-[0.14em] text-[var(--text-dim)]">{label}</p><p className="mt-[var(--space-xs)] font-mono text-2xl font-semibold">{value}</p><p className={`text-sm ${muted}`}>{delta}</p><Icon name="api" className="mr-[var(--space-xs)] inline h-3 w-3" /><ApiLabel>{endpoint}</ApiLabel></div>)}</div></Shell>; }
function CoverageHeatmap() { return <Shell dsId="ds:rtm-dashboard:coverage-heatmap" label="Panel 1: Coverage Heatmap"><div className="flex items-center justify-between gap-[var(--space-sm)]"><h3 className="font-semibold">Panel 1: Coverage Heatmap</h3><a className={`btn-secondary btn-sm ${focus}`} href="#surface-docs" data-action="EVENT_VIEW_DOC"><Icon name="docs" />Open docs</a></div><ul className="mt-[var(--space-sm)] grid gap-[var(--space-xs)]">{coverage.map(([id, title, cls, ratio, href]) => <li key={id}><a href={href} data-action="EVENT_HEATMAP_CLICK" className={`grid grid-cols-[1.5rem_minmax(0,1fr)_auto] items-center gap-[var(--space-sm)] rounded-[var(--radius)] p-[var(--space-xs)] hover:bg-[var(--bg)] ${focus}`}><span className={`heatmap-cell ${cls}`} aria-hidden="true" /><span><span className="block font-mono text-xs">{id}</span><span className={`block text-sm ${muted}`}>{title}</span></span><span className="font-mono text-xs">{ratio}</span></a></li>)}</ul></Shell>; }
function TaskProgress() { return <Shell dsId="ds:rtm-dashboard:task-progress" label="Panel 2: Task Progress"><h3 className="font-semibold">Panel 2: Task Progress</h3><div className="mt-[var(--space-sm)] space-y-[var(--space-sm)]">{[["Done","142","54.2%"],["In Review","37","14.1%"],["Blocked","16","6.1%"],["Ready","67","25.6%"]].map(([name,count,pct]) => <div key={name}><div className="mb-[var(--space-xs)] flex justify-between text-sm"><Status value={name} /><span className="font-mono">{count} · {pct}</span></div><div className="h-2 rounded-full bg-[var(--bg)]"><div className="h-2 rounded-full bg-[var(--accent-teal)]" style={{ width: pct }} /></div></div>)}</div><p className={`mt-[var(--space-sm)] text-xs ${muted}`}>Summary source <Icon name="api" className="mr-[var(--space-xs)] inline h-3 w-3" /><ApiLabel>GET /api/tasks?view=progress</ApiLabel>.</p></Shell>; }
function MiniGraph({ dsId }: { dsId: string }) { const isDashboard = dsId === "ds:rtm-dashboard:knowledge-graph-widget"; return <Shell dsId={dsId} label={isDashboard ? "Panel 3: Knowledge Graph" : undefined}><div className="flex items-center justify-between"><h3 className="font-semibold">{isDashboard ? "Panel 3: Knowledge Graph" : "Knowledge trace"}</h3><a href="#surface-trace" data-action="EVENT_VIEW_TRACE" className={`btn-secondary btn-sm ${focus}`}><Icon name="trace" />Open trace</a></div><ol className="mt-[var(--space-md)] grid grid-cols-5 items-center gap-[var(--space-xs)] text-center">{graphNodes.map((node, i) => <li key={node}><span className={`graph-node ${i === 0 ? "graph-node--prd" : i === 2 ? "graph-node--task" : i === 3 ? "graph-node--commit" : ""}`}>{node}</span></li>)}</ol><p className={`mt-[var(--space-sm)] text-xs ${muted}`}>Impact path from br-prd04-s5 to CI run gmind-webui-2841.</p></Shell>; }
function GapList() { return <Shell dsId="ds:rtm-dashboard:gap-analysis" label="Panel 4: Gap Analysis"><div className="flex items-center justify-between"><h3 className="font-semibold">Panel 4: Gap Analysis</h3><a href="#surface-tasks" data-action="EVENT_OPEN_CREATE_PLAN" className={`btn-primary btn-sm ${focus}`}><Icon name="task" />Create plan</a></div><ul className="mt-[var(--space-sm)] divide-y divide-[var(--border)]">{tasks.slice(0,3).map(([id,title,,status,priority]) => <li key={id} className="py-[var(--space-xs)]"><a href="#surface-task-detail" data-action="EVENT_VIEW_TASK" className={`block rounded-[var(--radius)] p-[var(--space-xs)] hover:bg-[var(--bg)] ${focus}`}><span className="font-mono text-xs">{id}</span><span className="block text-sm">{title}</span><Status value={priority || status} /></a></li>)}</ul></Shell>; }
function BoardSelector() { return <Shell dsId="ds:kanban:board-selector"><label className="block text-sm font-medium" htmlFor="board-select">Board view</label><select id="board-select" className={`mt-[var(--space-xs)] w-full rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)] p-[var(--space-xs)] ${focus}`} defaultValue="sprint"><option value="sprint">Sprint execution</option><option value="release">Release train</option><option value="bug-triage">Bug triage</option></select><Icon name="api" className="mr-[var(--space-xs)] inline h-3 w-3" /><ApiLabel>GET /api/tasks?view=board&board=sprint</ApiLabel></Shell>; }
function KanbanStats() { return <Shell dsId="ds:kanban:stats"><h3 className="font-semibold">Flow stats</h3><dl className="mt-[var(--space-sm)] grid grid-cols-3 gap-[var(--space-xs)] text-sm"><div><dt className={muted}>Cycle</dt><dd className="font-mono">4.7d</dd></div><div><dt className={muted}>WIP</dt><dd className="font-mono">16</dd></div><div><dt className={muted}>Blocked</dt><dd className="font-mono">3</dd></div></dl></Shell>; }
function EscalationBadge() { return <Shell dsId="ds:kanban:rte-escalation-badge" state="saving"><Status value="High" /> <span className="ml-[var(--space-xs)] text-sm">RTE escalation: CI boundary evidence overdue</span></Shell>; }
function KanbanColumns() { return <Shell dsId="ds:kanban:columns"><div className="grid gap-[var(--space-sm)] md:grid-cols-3">{lanes.map(([lane,id,title,owner,note]) => <section key={lane} aria-label={`${lane} lane`} className="rounded-[var(--radius)] bg-[var(--bg)] p-[var(--space-sm)]"><h3>{lane}</h3><a href="#surface-task-detail" data-action="EVENT_VIEW_TASK" className={`mt-[var(--space-sm)] block rounded-[var(--radius)] border border-[var(--border)] bg-[var(--surface)] p-[var(--space-sm)] ${focus}`}><span className="font-mono text-xs">{id}</span><span className="block font-medium">{title}</span><span className={`text-xs ${muted}`}>{owner} · {note}</span></a><button type="button" data-action="EVENT_MOVE_CARD" className={`mt-[var(--space-xs)] btn-secondary btn-sm ${focus}`}><Icon name="move" />Move to next lane</button></section>)}</div><Icon name="api" className="mr-[var(--space-xs)] inline h-3 w-3" /><ApiLabel>PUT /api/tasks/:id/status</ApiLabel></Shell>; }
function TaskFilters() { return <Shell dsId="ds:task-list:filters"><div className="grid gap-[var(--space-sm)] sm:grid-cols-3"><label>Status<select className={`mt-1 w-full rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)] p-[var(--space-xs)] ${focus}`} defaultValue="all"><option>all</option><option>blocked</option><option>review</option></select></label><label>Owner<input className={`mt-1 w-full rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)] p-[var(--space-xs)] ${focus}`} defaultValue="Nadia Ro" readOnly /></label><label>Trace<input className={`mt-1 w-full rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)] p-[var(--space-xs)] ${focus}`} defaultValue="br-prd04" readOnly /></label></div></Shell>; }
function TaskTable() { return <Shell dsId="ds:task-list:table"><table className="data-table w-full text-sm"><caption className="sr-only">Task list with sortable progress and trace links</caption><thead><tr><th><button data-action="EVENT_SORT_TASK" className={focus}>Task</button></th><th>Owner</th><th>Status</th><th>Priority</th><th>Trace</th></tr></thead><tbody>{tasks.map(([id,title,owner,status,priority,trace]) => <tr key={id} className={row}><td><a href="#surface-task-detail" data-action="EVENT_VIEW_TASK" className={focus}>{id}</a><span className={`block ${muted}`}>{title}</span></td><td>{owner}</td><td><Status value={status} /></td><td><Status value={priority} /></td><td><a href="#surface-trace" data-action="EVENT_VIEW_TRACE" className={`font-mono ${focus}`}>{trace}</a></td></tr>)}</tbody></table><ApiLabel>GET /api/tasks?format=list</ApiLabel></Shell>; }
function BulkActions() { return <Shell dsId="ds:task-list:bulk-actions"><button type="button" data-action="EVENT_BULK_UPDATE" className={`btn-secondary btn-sm ${focus}`}><Icon name="move" />Bulk move selected through API</button> <ApiLabel>PUT /api/tasks/bulk</ApiLabel></Shell>; }
function TaskDetailFields() { return <Shell dsId="ds:task-detail:editable-fields" state="saving"><WorkspaceStatePanel state="saving" compact /><label className="mt-[var(--space-sm)] block text-sm font-medium" htmlFor="task-description">Description preview</label><textarea id="task-description" className={`mt-[var(--space-xs)] min-h-28 w-full rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)] p-[var(--space-sm)] text-sm ${focus}`} readOnly value="Validate approve and reject decisions through the Go REST approval endpoint. Attach PRD trace, test result, and PM decision notes before moving to Done." /><a href="#event-field-edit" data-action="EVENT_FIELD_EDIT" className={`mt-[var(--space-sm)] inline-flex btn-secondary btn-sm ${focus}`}><Icon name="saving" />Save draft through API</a></Shell>; }
function TaskTabs() { return <Shell dsId="ds:task-detail:tabs"><nav aria-label="Task detail tabs" className="flex flex-wrap gap-[var(--space-xs)]">{["detail","activity","graph","code","approval"].map(tab => <a key={tab} href={`#${tab}`} data-action="EVENT_TAB_CLICK" className={`btn-secondary btn-sm ${focus}`}>{tab}</a>)}</nav></Shell>; }
function ActivityFeed() { return <Shell dsId="ds:task-detail:activity"><h3 className="font-semibold">Activity</h3><ol className="mt-[var(--space-sm)] space-y-[var(--space-xs)]">{activity.map(item => <li key={item} className="border-l border-[var(--border-highlight)] pl-[var(--space-sm)] text-sm">{item}</li>)}</ol></Shell>; }
function ApprovalQueue() { return <Shell dsId="ds:approval:queue" label="Queue Panel"><h3 className="font-semibold">Queue Panel</h3><ul className="mt-[var(--space-sm)] divide-y divide-[var(--border)]">{tasks.slice(0,3).map(([id,title,owner,,priority]) => <li key={id} className="py-[var(--space-xs)]"><a href="#panels" data-action="EVENT_APPROVAL_SELECT" className={`block rounded-[var(--radius)] p-[var(--space-xs)] hover:bg-[var(--bg)] ${focus}`}><span className="font-mono text-xs">{id}</span><span className="block text-sm font-medium">{title}</span><span className={`text-xs ${muted}`}>{owner} · {priority} priority</span></a></li>)}</ul></Shell>; }
function EvidenceHub() { return <Shell dsId="ds:approval:evidence-hub" label="Evidence Hub"><h3 className="font-semibold">Evidence Hub</h3>{["Code diff: webui-pm-workspace route", "Test result: target page eslint passed", "Beads trace: br-prd04-s5 to bd-approval-178", "PRD context: HITL supervision"].map(item => <p key={item} className="mt-[var(--space-xs)] rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)] p-[var(--space-xs)] text-sm">{item}</p>)}<ApiLabel>GET /api/approval/:id/evidence</ApiLabel></Shell>; }
function RtmMatrix() { return <Shell dsId="ds:approval:rtm-matrix"><h3 className="font-semibold">RTM matrix evidence</h3><table className="data-table mt-[var(--space-sm)] w-full text-sm"><thead><tr><th>PRD</th><th>Task</th><th>Test</th></tr></thead><tbody>{coverage.slice(0,3).map(([id,title,,ratio]) => <tr key={id} className={row}><td className="font-mono">{id}</td><td>{title}</td><td>{ratio}</td></tr>)}</tbody></table></Shell>; }
function DecisionBox() { return <Shell dsId="ds:approval:decision-controls" state="insufficient_evidence" label="Decision Box"><h3 className="sr-only">Decision Box</h3><WorkspaceStatePanel state="insufficient_evidence" compact /><div className="mt-[var(--space-sm)] flex flex-wrap gap-[var(--space-xs)]"><a href="#approval-approved" data-action="EVENT_APPROVAL_DECISION" data-decision="approved" className={`btn-primary btn-sm ${focus}`}><Icon name="approve" />Approve via API</a><a href="#approval-rejected" data-action="EVENT_APPROVAL_DECISION" data-decision="rejected" className={`btn-danger btn-sm ${focus}`}><Icon name="reject" />Reject via API</a><a href="#approval-changes" data-action="EVENT_REQUEST_CHANGES" data-decision="changes-requested" className={`btn-secondary btn-sm ${focus}`}><Icon name="changes" />Request changes</a></div><ApiLabel>POST /api/approval/:id/decision</ApiLabel></Shell>; }
function TraceToolbar() { return <Shell dsId="ds:trace-explorer:toolbar"><div className="flex flex-wrap items-center gap-[var(--space-xs)]"><button className={`btn-secondary btn-sm ${focus}`} data-action="EVENT_VIEW_TRACE"><Icon name="trace" />Depth full</button><button className={`btn-secondary btn-sm ${focus}`} data-action="EVENT_FILTER_TRACE"><Icon name="filter" />Show PRD to CI</button><ApiLabel>GET /api/graph/presets</ApiLabel></div></Shell>; }
function TraceGraph() { return <Shell dsId="ds:trace-explorer:graph-canvas" state="partial"><WorkspaceStatePanel state="partial" compact /><div className="mt-[var(--space-sm)] grid grid-cols-5 gap-[var(--space-xs)]">{graphNodes.map((node, i) => <a key={node} href={i === 2 ? "#surface-task-detail" : "#surface-docs"} data-action={i === 2 ? "EVENT_VIEW_TASK" : "EVENT_VIEW_DOC"} className={`graph-node ${i === 0 ? "graph-node--prd" : i === 2 ? "graph-node--task" : i === 3 ? "graph-node--commit" : ""} ${focus}`}>{node}</a>)}</div></Shell>; }
function DagLayers() { return <Shell dsId="ds:trace-explorer:dag-layers"><ol className="grid gap-[var(--space-xs)] sm:grid-cols-5">{["prd-sections","plan-elements","tasks","commits","ci"].map(layer => <li key={layer} className="rounded-[var(--radius)] bg-[var(--bg)] p-[var(--space-xs)] text-sm">{layer}</li>)}</ol></Shell>; }
function NodeDetail() { return <Shell dsId="ds:trace-explorer:detail-panel"><h3 className="font-semibold">Selected node</h3><dl className="mt-[var(--space-sm)] grid gap-[var(--space-xs)] text-sm"><dt className="font-mono text-xs text-[var(--text-dim)]">Beads ID</dt><dd>br-prd04-s5</dd><dt className="font-mono text-xs text-[var(--text-dim)]">Impact</dt><dd>Approval gate, task detail, QA evidence, Go API adapter.</dd></dl></Shell>; }
function DocTree() { return <Shell dsId="ds:doc-viewer:tree"><h3 className="font-semibold">Document tree</h3><ul className="path-tree mt-[var(--space-sm)]">{docs.map(doc => <li key={doc}><a href={`#${doc.toLowerCase().replaceAll(" ", "-")}`} data-action="EVENT_VIEW_DOC" className={focus}>{doc}</a></li>)}</ul></Shell>; }
function MarkdownViewer() { return <Shell dsId="ds:doc-viewer:content"><h3 className="font-semibold">PRD-04 excerpt</h3><p className="mt-[var(--space-sm)] text-sm">The PM Workspace supervises the Pyramid of Knowledge through Go REST endpoints. Browser actions navigate to documents and trace IDs; repository, database, shell, and CI operations remain server-side.</p><a href="#surface-trace" data-action="EVENT_VIEW_TRACE" className={`mt-[var(--space-sm)] inline-flex badge badge-cyan ${focus}`}>br-prd04-s5</a></Shell>; }
function SectionBadges() { return <Shell dsId="ds:doc-viewer:section-badges"><div className="flex flex-wrap gap-[var(--space-xs)]">{coverage.slice(0,4).map(([id,, ,ratio]) => <a key={id} href="#surface-trace" data-action="EVENT_BEADS_ID_CLICK" className={`badge badge-cyan ${focus}`}>{id} · {ratio}</a>)}</div></Shell>; }
function SearchInput() { return <Shell dsId="ds:search-explorer:input"><form action="#surface-search" data-action="EVENT_SEARCH"><label className="block text-sm font-medium" htmlFor="search-explorer-query">Search query</label><input id="search-explorer-query" name="q" defaultValue="approval evidence" className={`mt-1 w-full rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)] p-[var(--space-xs)] ${focus}`} /><button className={`mt-[var(--space-xs)] btn-primary btn-sm ${focus}`}><Icon name="search" />Search API</button></form></Shell>; }
function TypeFilters() { return <Shell dsId="ds:search-explorer:type-filters"><nav aria-label="Search type filters" className="flex flex-wrap gap-[var(--space-xs)]">{["all","doc","commit","task","adr","chat","spike"].map(type => <a href={`#${type}`} data-action="EVENT_SEARCH_FILTER" className={`btn-secondary btn-sm ${focus}`} key={type}>{type}</a>)}</nav></Shell>; }
function SearchResults() { return <Shell dsId="ds:search-explorer:results"><h3 className="font-semibold">Grouped results</h3><ul className="mt-[var(--space-sm)] divide-y divide-[var(--border)]">{searchResults.map(([type,id,title,action,href]) => <li key={id} className="py-[var(--space-xs)]"><a href={href} data-action={action} className={`block rounded-[var(--radius)] p-[var(--space-xs)] hover:bg-[var(--bg)] ${focus}`}><span className="badge badge-cyan">{type}</span><span className="ml-[var(--space-xs)] font-mono text-xs">{id}</span><span className="block text-sm">{title}</span></a></li>)}</ul><ApiLabel>GET /api/search?q=approval evidence&type=all</ApiLabel></Shell>; }
function Fallback({ dsId }: { dsId: string }) { return <Shell dsId={dsId}><p className="font-mono text-xs text-[var(--text-dim)]">{dsId}</p><p className="mt-[var(--space-xs)] text-sm">Component mapping retained for contract traceability.</p></Shell>; }
