"use client";

import { FormEvent, KeyboardEvent, ReactNode, Ref, useEffect, useMemo, useRef, useState } from "react";

type ViewState = "default" | "loading" | "empty" | "error" | "offline" | "forbidden" | "partial" | "saving" | "bulk_action_processing" | "pending" | "success" | "rehydrating" | "not_found" | "sync_conflict" | "insufficient_evidence" | "decision_submitted";
type Region = { type: string; dsId: string; actions?: string };
type Screen = { id: string; label: string; route: string; dsId: string; rootDsId: string; layout: string; states: ViewState[]; regions: Region[]; endpoints: string[]; anchors?: string[] };
type WorkspaceProps = { initialActiveId?: string; storyboardId?: string };
type EventName = "EVENT_ROUTE_ENTER" | "EVENT_HASH_NAVIGATE" | "EVENT_REFRESH" | "EVENT_RETRY" | "EVENT_SEARCH" | "EVENT_VIEW_TASK" | "EVENT_VIEW_TRACE" | "EVENT_VIEW_DOC" | "EVENT_SAVE_TASK" | "EVENT_SAVE_BULK" | "EVENT_MOVE_CARD" | "EVENT_APPROVAL_DECISION" | "EVENT_PI_PLAN_SAVE" | "EVENT_CONFIDENCE_VOTE" | "EVENT_DISCONNECT" | "EVENT_RECONNECT" | "EVENT_KEEP_LOCAL" | "EVENT_USE_SERVER" | "EVENT_BACK" | "EVENT_OPEN_OVERLAY" | "EVENT_CLOSE_OVERLAY";
type ComponentContext = { status: ViewState; query: string; taskOwner: string; taskPriority: string; vote: string; approvalReason: string; overlayOpen: boolean; onAction: (event: EventName, detail: string) => void; setStatus: (value: ViewState) => void; setQuery: (value: string) => void; setTaskOwner: (value: string) => void; setTaskPriority: (value: string) => void; setVote: (value: string) => void; setApprovalReason: (value: string) => void };

const baseStates: ViewState[] = ["default", "loading", "empty", "error", "offline", "forbidden"];
const shellStates: ViewState[] = [...baseStates, "saving", "rehydrating", "sync_conflict", "success"];
const allStates: ViewState[] = ["default", "loading", "empty", "error", "offline", "forbidden", "partial", "saving", "bulk_action_processing", "pending", "success", "rehydrating", "not_found", "sync_conflict", "insufficient_evidence", "decision_submitted"];
const focusRing = "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-cyan)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--bg)]";
const panel = "rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface)]";
const inset = "rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)]";
const chip = "rounded-full border border-[var(--border)] px-[var(--space-sm)] py-[var(--space-xs)] font-mono text-[0.68rem] uppercase tracking-[0.12em] text-[var(--text-dim)]";
const motion = "transition-[opacity,transform] duration-[var(--duration-normal)] ease-[var(--ease-out)]";
function region(type: string, dsId: string, actions?: string): Region { return { type, dsId, actions } }

const screens: Screen[] = [
  { id: "screen:rtm-dashboard", label: "RTM Dashboard", route: "/", dsId: "ds:screen:rtm-dashboard-001", rootDsId: "ds:rtm-dashboard:root", layout: "KPI row above coverage heatmap, task progress, knowledge graph widget, and gap analysis.", states: baseStates, regions: [region("KpiCards", "ds:rtm-dashboard:kpis"), region("CoverageHeatmap", "ds:rtm-dashboard:coverage-heatmap", "EVENT_VIEW_TRACE"), region("TaskProgressPanel", "ds:rtm-dashboard:task-progress", "EVENT_VIEW_TASK"), region("KnowledgeGraphWidget", "ds:rtm-dashboard:knowledge-graph-widget", "EVENT_VIEW_TRACE"), region("GapAnalysisList", "ds:rtm-dashboard:gap-analysis", "EVENT_REFRESH")], endpoints: ["GET /api/coverage", "GET /api/tasks", "GET /api/trace/:id?depth=2", "GET /api/gaps"], anchors: ["surface-rtm-dashboard"] },
  { id: "screen:safe-board", label: "SAFe Board", route: "/board", dsId: "ds:screen:kanban-001", rootDsId: "ds:kanban:root", layout: "Hash-selected SAFe board with WIP badges, draggable-card zone, stats strip, and RTE escalation badge.", states: [...baseStates, "saving"], regions: [region("BoardSelector", "ds:kanban:board-selector", "EVENT_HASH_NAVIGATE"), region("KanbanColumns", "ds:kanban:columns", "EVENT_MOVE_CARD, EVENT_VIEW_TASK"), region("BoardStats", "ds:kanban:stats"), region("RteEscalationBadge", "ds:kanban:rte-escalation-badge")], endpoints: ["GET /api/tasks?view=board&board=<id>", "PUT /api/tasks/:id/status", "GET /api/tasks/:id/activity"], anchors: ["sprint", "release", "bug-triage"] },
  { id: "screen:task-list", label: "Task List", route: "/tasks", dsId: "ds:screen:task-list-001", rootDsId: "ds:task-list:root", layout: "Filter rail, sortable task table shell, mobile card-list fallback, pagination, and bulk action bar.", states: [...baseStates, "saving", "bulk_action_processing"], regions: [region("TaskFilters", "ds:task-list:filters"), region("TaskTable", "ds:task-list:table", "EVENT_VIEW_TASK"), region("BulkActionBar", "ds:task-list:bulk-actions", "EVENT_SAVE_BULK")], endpoints: ["GET /api/tasks?format=list", "PUT /api/tasks/bulk"], anchors: ["surface-task-list"] },
  { id: "screen:task-detail", label: "Task Detail", route: "/tasks/:id", dsId: "ds:screen:task-detail-001", rootDsId: "ds:task-detail:root", layout: "Editable task header with Detail, Activity, Graph, Code, and approval-linked tab regions.", states: [...baseStates, "saving", "not_found"], regions: [region("EditableFieldGroup", "ds:task-detail:editable-fields", "EVENT_SAVE_TASK"), region("TaskTabs", "ds:task-detail:tabs", "EVENT_HASH_NAVIGATE"), region("ActivityTimeline", "ds:task-detail:activity"), region("MiniGraphWidget", "ds:task-detail:graph-widget", "EVENT_VIEW_TRACE")], endpoints: ["GET /api/tasks/:id", "GET /api/tasks/:id/activity", "GET /api/trace/:id?depth=2", "PUT /api/tasks/:id"], anchors: ["detail", "activity", "graph", "code", "approval", "surface-task-detail"] },
  { id: "screen:approval-gates", label: "Approval Gates", route: "/approval", dsId: "ds:screen:approval-001", rootDsId: "ds:approval:root", layout: "Queue, evidence hub, RTM matrix, coverage heatmap, decision box, and audit receipt split.", states: [...baseStates, "insufficient_evidence", "decision_submitted"], regions: [region("ApprovalQueue", "ds:approval:queue"), region("EvidenceHub", "ds:approval:evidence-hub"), region("RtmMatrix", "ds:approval:rtm-matrix"), region("DecisionControls", "ds:approval:decision-controls", "EVENT_APPROVAL_DECISION")], endpoints: ["GET /api/tasks?status=pending-approval", "GET /api/approval/:id/evidence", "GET /api/coverage", "POST /api/approval/:id/decision"], anchors: ["panels", "rtm", "heatmap", "surface-approval-gates"] },
  { id: "screen:doc-viewer", label: "Doc Viewer", route: "/docs", dsId: "ds:screen:doc-viewer-001", rootDsId: "ds:doc-viewer:root", layout: "Source-type document tree beside rendered document panel with Beads badges and coverage markers.", states: baseStates, regions: [region("DocTree", "ds:doc-viewer:tree"), region("RenderedDocument", "ds:doc-viewer:content", "EVENT_VIEW_TRACE"), region("SectionCoverageBadges", "ds:doc-viewer:section-badges")], endpoints: ["GET /api/docs?group=source_type", "GET /api/docs/:id", "GET /api/coverage?doc=<id>"], anchors: ["surface-doc-viewer"] },
  { id: "screen:trace-explorer", label: "Trace Explorer", route: "/trace/:id", dsId: "ds:screen:trace-explorer-001", rootDsId: "ds:trace-explorer:root", layout: "Graph canvas or layered DAG with toolbar, presets, legends, selected-node banner, and detail sidebar.", states: [...baseStates, "partial"], regions: [region("TraceToolbar", "ds:trace-explorer:toolbar"), region("GraphCanvas", "ds:trace-explorer:graph-canvas", "EVENT_VIEW_TASK, EVENT_VIEW_DOC"), region("TraversalLayers", "ds:trace-explorer:dag-layers"), region("DetailPanel", "ds:trace-explorer:detail-panel")], endpoints: ["GET /api/trace/:id?depth=full", "GET /api/graph/presets", "GET /api/impact/:section"], anchors: ["simple", "ecosystem", "sprint", "prd-sections", "plan-elements", "tasks", "commits", "surface-trace-explorer"] },
  { id: "screen:search-explorer", label: "Search Explorer", route: "/search", dsId: "ds:screen:explorer-001", rootDsId: "ds:search-explorer:root", layout: "Unified search with query input, hash-selected filters, grouped result list, and detail sidebar drawer fallback.", states: baseStates, regions: [region("SearchInput", "ds:search-explorer:input", "EVENT_SEARCH"), region("TypeFilters", "ds:search-explorer:type-filters", "EVENT_HASH_NAVIGATE"), region("GroupedResults", "ds:search-explorer:results", "EVENT_VIEW_TASK, EVENT_VIEW_DOC, EVENT_VIEW_TRACE")], endpoints: ["GET /api/search?q=<query>&type=<type>"], anchors: ["all", "doc", "commit", "task", "adr", "chat", "spike", "surface-search-results"] },
  { id: "screen:terminal-console", label: "Terminal Console", route: "/terminal", dsId: "ds:screen:terminal-001", rootDsId: "ds:terminal:root", layout: "Scenario tabs above a 2x2 read-only terminal mosaic for agent, deploy, debug, and CI/CD streams.", states: baseStates, regions: [region("ScenarioTabs", "ds:terminal:scenario-tabs", "EVENT_HASH_NAVIGATE"), region("TerminalMosaic", "ds:terminal:mosaic"), region("TerminalLineList", "ds:terminal:line-list")], endpoints: ["GET /api/agents/sessions", "GET /api/ci/runs", "GET /api/tasks/:id/activity", "STREAM /api/log-events?stream=terminal"], anchors: ["agent-console", "deploy", "debug", "ci-cd"] },
  { id: "screen:portfolio", label: "Portfolio", route: "/portfolio", dsId: "ds:screen:portfolio-001", rootDsId: "ds:portfolio:root", layout: "Executive epic table beside Q1/Q2/Q3 2026 roadmap with budget, progress, status, owner, and forecast.", states: baseStates, regions: [region("PortfolioTable", "ds:portfolio:epic-table", "EVENT_VIEW_TASK"), region("Roadmap", "ds:portfolio:roadmap")], endpoints: ["GET /api/portfolio/epics", "GET /api/tasks?issue_type=epic"] },
  { id: "screen:pi-planning", label: "PI Planning", route: "/pi-planning", dsId: "ds:screen:pi-planning-001", rootDsId: "ds:pi-planning:root", layout: "Strategic sandbox, capacity plan, business value scoring, confidence vote, and ROAM board.", states: [...baseStates, "saving", "pending"], regions: [region("StrategicSandbox", "ds:pi-planning:strategic-sandbox", "EVENT_PI_PLAN_SAVE"), region("BusinessValueScoring", "ds:pi-planning:value-scoring"), region("ConfidenceVote", "ds:pi-planning:confidence-vote", "EVENT_CONFIDENCE_VOTE"), region("RoamBoard", "ds:pi-planning:roam-board")], endpoints: ["GET /api/pi/features", "PUT /api/pi/plan", "GET /api/risks?view=roam", "POST /api/pi/confidence-vote"] },
  { id: "screen:git-graph", label: "Git Graph", route: "/git-graph", dsId: "ds:screen:git-graph-001", rootDsId: "ds:git-graph:root", layout: "Scenario selector and graph canvas with branches, commits, merge connections, branch tags, stats, and trace overlay.", states: baseStates, regions: [region("ScenarioSelector", "ds:git-graph:scenario-selector", "EVENT_HASH_NAVIGATE"), region("GitGraphCanvas", "ds:git-graph:canvas"), region("CommitDetail", "ds:git-graph:commit-detail", "EVENT_VIEW_TRACE")], endpoints: ["GET /api/git/graph?scenario=<id>", "GET /api/trace/:id?include=git"], anchors: ["gitflow", "multi-agent", "hotfix", "release-train", "monorepo", "beads-prd-trace", "beads-deadlock", "beads-ds-comp", "beads-traversal", "beads-sprint-review"] },
  { id: "screen:timeline", label: "Timeline", route: "/timeline", dsId: "ds:screen:timeline-001", rootDsId: "ds:timeline:root", layout: "File lease indicators, activity feed, sprint day timeline, and freshness indicator.", states: baseStates, regions: [region("FileLeasePanel", "ds:timeline:file-lease-panel"), region("ActivityFeed", "ds:timeline:activity-feed", "EVENT_VIEW_TASK"), region("SprintDayTimeline", "ds:timeline:sprint-day")], endpoints: ["GET /api/activity", "GET /api/file-leases", "GET /api/tasks/:id/activity"], anchors: ["file-lease", "activity-feed", "sprint-day"] },
  { id: "screen:components-catalog", label: "Components Catalog", route: "/design-system/components", dsId: "ds:screen:components-001", rootDsId: "ds:components-catalog:root", layout: "Catalog of shared primitives with hash section navigation and interactive example slots.", states: baseStates, regions: [region("ComponentSectionNav", "ds:components-catalog:section-nav", "EVENT_HASH_NAVIGATE"), region("ComponentExamples", "ds:components-catalog:examples")], endpoints: ["GET /api/design-system/components"], anchors: ["buttons", "badges-status", "progress", "avatar-stack", "skeleton", "empty-state", "error-banner"] },
  { id: "screen:storyboard-overview", label: "Storyboard Overview", route: "/storyboards", dsId: "ds:screen:storyboard-001", rootDsId: "ds:storyboard-overview:root", layout: "Journey filter, horizontal use-case flow nodes, guidance panel, and CTA to real screen.", states: baseStates, regions: [region("JourneyFilter", "ds:storyboard-overview:filter"), region("UsecaseFlow", "ds:storyboard-overview:flow"), region("GuidancePanel", "ds:storyboard-overview:guidance")], endpoints: ["GET /api/storyboards"] },
  { id: "screen:storyboard-detail", label: "Storyboard Detail", route: "/storyboards/:id", dsId: "ds:screen:storyboard-detail-001", rootDsId: "ds:storyboard-detail:root", layout: "Role panel, journey summary, step timeline, related use cases, expected states, and CTA to matching Core route.", states: [...baseStates, "not_found"], regions: [region("StoryboardRolePanel", "ds:storyboard-detail:role-panel"), region("StepTimeline", "ds:storyboard-detail:step-timeline"), region("RelatedUsecases", "ds:storyboard-detail:related-usecases")], endpoints: ["GET /api/storyboards/:id"] },
  { id: "screen:document-graph-widget", label: "Document Graph Widget", route: "embedded", dsId: "ds:screen:document-graph-widget-001", rootDsId: "ds:document-graph-widget:root", layout: "Embedded graph widget with canvas, filters, zoom controls, side panel, and Open Full Page CTA.", states: baseStates, regions: [region("MiniGraphCanvas", "ds:document-graph-widget:canvas"), region("NodeDetailPanel", "ds:document-graph-widget:detail-panel", "EVENT_VIEW_TRACE")], endpoints: ["GET /api/trace/:id?depth=2"] }
];

const aliases: Record<string, string> = { "screen:ds-terminal": "screen:terminal-console", "screen:ds-portfolio": "screen:portfolio", "screen:ds-pi-planning": "screen:pi-planning", "screen:ds-git-graph": "screen:git-graph", "screen:ds-kanban": "screen:safe-board", "screen:ds-knowledge-graph": "screen:trace-explorer", "screen:ds-approval": "screen:approval-gates", "screen:ds-timeline": "screen:timeline", "screen:ds-components": "screen:components-catalog", "screen:ds-doc-viewer": "screen:doc-viewer", "screen:ds-explorer": "screen:search-explorer", "screen:ds-beads-traversal": "screen:trace-explorer", "screen:ds-storyboard": "screen:storyboard-overview", "screen:ds-storyboard-detail": "screen:storyboard-detail" };
const surfaceAnchors: Record<string, string> = { "screen:rtm-dashboard": "surface-rtm-dashboard", "screen:safe-board": "surface-safe-board", "screen:task-list": "surface-task-list", "screen:task-detail": "surface-task-detail", "screen:trace-explorer": "surface-trace-explorer", "screen:doc-viewer": "surface-doc-viewer", "screen:approval-gates": "surface-approval-gates", "screen:search-explorer": "surface-search-results" };
const metrics = [{ k: "PRD coverage", v: "87.4%", d: "br-prd04 sections linked" }, { k: "Open beads", v: "143", d: "GET /api/tasks" }, { k: "Trace depth", v: "6 hops", d: "GET /api/trace/:id" }, { k: "Policy gaps", v: "11", d: "GET /api/gaps" }];
const tasks = [{ id: "bd-webui-shell", title: "Wire Core route dispatcher", owner: "Mina Rourke", status: "In review", prio: "P1", cov: "91.3%" }, { id: "bd-rtm-graph", title: "Bind trace widget to PRD coverage", owner: "Oren Valdez", status: "Blocked", prio: "P0", cov: "62.7%" }, { id: "bd-safe-board", title: "Persist SAFe WIP status updates", owner: "Linh Okafor", status: "Ready", prio: "P2", cov: "78.6%" }];
const docs = ["PRD-04 WebUI and PM Workspace", "PRD-02 Universal Tracking and RTM", "Plan: Ralph Loop route parity"];
const storySteps = ["Load route data", "Inspect evidence", "Submit audited decision"];
const contractAliases = ["header-panel", "task-table", "detail-layout", "task-info", "search-layout", "filter-sidebar", "results-list", "result-item", "terminal-view", "console-pane", "timeline-view", "git-graph-view", "scenario-list", "storyboard-view", "journey-filter", "usecase-flow", "step-node", "ds:terminal:agent-console", "ds:terminal:deploy", "ds:terminal:debug", "ds:terminal:ci-cd", "ds:table:portfolio", "ds:roadmap:main", "ds:canvas:git-graph", "ds:list:scenarios", "ds:selector:board", "ds:columns:kanban", "ds:canvas:knowledge-graph", "ds:panel:queue", "ds:hub:evidence", "ds:box:decision", "ds:feed:activity", "ds:list:file-leases", "ds:dnd:strategic-sandbox", "ds:board:roam", "ds:list:presets"];

export default function WebUIPMWorkspacePage({ initialActiveId, storyboardId }: WorkspaceProps = {}) {
  const activeId = initialActiveId ? aliases[initialActiveId] ?? initialActiveId : "screen:rtm-dashboard";
  const activeScreen = screens.find((screen) => screen.id === activeId) ?? screens[0];
  const orderedScreens = [activeScreen, ...screens.filter((screen) => screen.id !== activeScreen.id)];
  const [query, setQuery] = useState("coverage br-prd04");
  const [status, setStatus] = useState<ViewState>("default");
  const [overlayOpen, setOverlayOpen] = useState(false);
  const [taskOwner, setTaskOwner] = useState("Mina Rourke");
  const [taskPriority, setTaskPriority] = useState("P1");
  const [vote, setVote] = useState("4");
  const [approvalReason, setApprovalReason] = useState("Evidence links cover PRD, plan, task, and commit trail.");
  const [log, setLog] = useState("Route entered through EVENT_ROUTE_ENTER");
  const searchRef = useRef<HTMLInputElement>(null);
  const dialogRef = useRef<HTMLDivElement>(null);
  const closeOverlayRef = useRef<HTMLButtonElement>(null);
  const lastFocusedRef = useRef<HTMLElement | null>(null);
  const ctx = useMemo<ComponentContext>(() => ({ status, query, taskOwner, taskPriority, vote, approvalReason, overlayOpen, setStatus, setQuery, setTaskOwner, setTaskPriority, setVote, setApprovalReason, onAction: (event, detail) => { setLog(`${event}: ${detail}`); if (event === "EVENT_OPEN_OVERLAY") { lastFocusedRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setOverlayOpen(true); } if (event === "EVENT_CLOSE_OVERLAY") { setOverlayOpen(false); window.setTimeout(() => lastFocusedRef.current?.focus(), 0); } if (event === "EVENT_DISCONNECT") setStatus("offline"); if (event === "EVENT_RECONNECT") { setStatus("rehydrating"); window.setTimeout(() => setStatus("sync_conflict"), 180); } if (["EVENT_KEEP_LOCAL", "EVENT_USE_SERVER"].includes(event)) { setStatus("rehydrating"); window.setTimeout(() => setStatus("success"), 180); } if (["EVENT_BACK", "EVENT_RETRY", "EVENT_REFRESH"].includes(event)) { setStatus("loading"); window.setTimeout(() => setStatus("default"), 180); } if (event === "EVENT_SAVE_BULK") setStatus("bulk_action_processing"); if (["EVENT_SAVE_TASK", "EVENT_MOVE_CARD", "EVENT_PI_PLAN_SAVE"].includes(event)) setStatus("saving"); if (event === "EVENT_CONFIDENCE_VOTE") setStatus("decision_submitted"); if (event === "EVENT_APPROVAL_DECISION") setStatus(approvalReason.length > 24 ? "decision_submitted" : "insufficient_evidence"); } }), [approvalReason, overlayOpen, query, status, taskOwner, taskPriority, vote]);
  useEffect(() => { const onKey = (event: globalThis.KeyboardEvent) => { const target = event.target as HTMLElement; const editable = ["INPUT", "TEXTAREA", "SELECT"].includes(target.tagName); if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); searchRef.current?.focus(); setLog("EVENT_SEARCH: keyboard shortcut focused global search"); } if (event.key === "/" && !editable) { event.preventDefault(); searchRef.current?.focus(); setLog("EVENT_SEARCH: slash shortcut focused global search"); } if (event.key === "Escape" && overlayOpen) ctx.onAction("EVENT_CLOSE_OVERLAY", "Escape closed mobile navigation overlay"); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [ctx, overlayOpen]);
  useEffect(() => { if (overlayOpen) closeOverlayRef.current?.focus(); }, [overlayOpen]);
  const submitSearch = (event: FormEvent) => { event.preventDefault(); setStatus("loading"); setLog(`EVENT_SEARCH: GET /api/search?q=${query}&type=all`); window.setTimeout(() => setStatus(query.trim() ? "default" : "empty"), 180); };
  const trapDialogFocus = (event: KeyboardEvent<HTMLDivElement>) => { if (event.key !== "Tab" || !dialogRef.current) return; const focusable = Array.from(dialogRef.current.querySelectorAll<HTMLElement>("a[href], button:not([disabled]), input:not([disabled]), textarea:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex='-1'])")); const first = focusable[0]; const last = focusable[focusable.length - 1]; if (!first || !last) return; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };

  return <main data-screen-id="screen:global-shell" data-ds-id="ds:screen:webui-pm-workspace-001" data-state={status} className="min-h-[100dvh] bg-[var(--bg)] text-[var(--text)]">
    <a href="#active-surface" className={`sr-only focus:not-sr-only focus:fixed focus:left-[var(--space-md)] focus:top-[var(--space-md)] focus:z-50 focus:rounded-[var(--radius)] focus:bg-[var(--surface-elevated)] focus:p-[var(--space-sm)] ${focusRing}`}>Skip to PM workspace surfaces</a>
    <section data-ds-id="ds:global-shell:root" className="mx-auto grid min-h-[100dvh] w-full max-w-screen-2xl grid-rows-[auto_1fr_auto] border-x border-[var(--border)] bg-[var(--surface)]">
      <header data-ds-id="ds:global-shell:header" className="border-b border-[var(--border)] p-[var(--space-md)] md:p-[var(--space-lg)]"><div className="grid gap-[var(--space-md)] lg:grid-cols-[minmax(0,1fr)_minmax(18rem,32rem)_auto] lg:items-end"><section aria-labelledby="workspace-title"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[var(--text-dim)]">PRD-04 WebUI PM Workspace</p><h1 id="workspace-title" className="mt-[var(--space-xs)] text-3xl font-semibold tracking-tight">Go REST API workspace shell</h1><p className="mt-[var(--space-sm)] max-w-3xl text-sm text-[var(--text-dim)]">PM surfaces consume normalized gmind serve endpoints; browser controls never touch FrankenSQLite, shell, git, gh, FastCode, or CI providers directly.</p></section><form role="search" aria-label="Global PM workspace search" onSubmit={submitSearch} className="grid gap-[var(--space-sm)]"><label htmlFor="workspace-search" className="text-xs text-[var(--text-dim)]">Global search, Ctrl+K or slash</label><input ref={searchRef} id="workspace-search" value={query} onChange={(e) => setQuery(e.target.value)} className={`${inset} px-[var(--space-md)] py-[var(--space-sm)] text-sm text-[var(--text)] ${focusRing}`} /><div className="flex flex-wrap gap-[var(--space-xs)]"><Button>Search through GET /api/search</Button><Button onClick={() => ctx.onAction("EVENT_OPEN_OVERLAY", "mobile navigation opened")}>Open nav overlay</Button></div></form><SyncBanner ctx={ctx} log={log} /></div><StateControls ctx={ctx} /></header>
      <div className="grid min-h-0 md:grid-cols-[16rem_minmax(0,1fr)] xl:grid-cols-[18rem_minmax(0,1fr)]"><div className="hidden md:block"><Sidebar ctx={ctx} activeId={activeScreen.id} mobile={false} /></div><section id="active-surface" data-ds-id="ds:global-shell:active-surface" aria-labelledby="active-surface-title" tabIndex={-1} className="min-w-0 overflow-auto bg-[var(--bg)] p-[var(--space-md)] md:p-[var(--space-lg)]"><article className={`${panel} p-[var(--space-md)]`}><p className="font-mono text-xs uppercase tracking-[0.18em] text-[var(--text-dim)]">Active contract surface</p><h2 id="active-surface-title" className="mt-[var(--space-xs)] text-2xl font-semibold">{activeScreen.label}</h2><p className="mt-[var(--space-xs)] text-sm text-[var(--text-dim)]">{activeScreen.layout}</p>{storyboardId ? <p className="mt-[var(--space-xs)] font-mono text-xs text-[var(--text-dim)]">Storyboard route id: {storyboardId}</p> : null}</article><div className="mt-[var(--space-md)] grid gap-[var(--space-md)]">{orderedScreens.map((screen) => <ScreenShell key={screen.id} screen={screen} featured={screen.id === activeScreen.id} ctx={ctx} />)}</div></section></div>
      {overlayOpen ? <div role="dialog" aria-modal="true" aria-label="Mobile workspace navigation" ref={dialogRef} onKeyDown={trapDialogFocus} className={`${motion} fixed inset-0 z-40 bg-[var(--bg)] p-[var(--space-md)] md:hidden`}><div className={`${panel} max-h-full overflow-auto p-[var(--space-md)]`}><div className="mb-[var(--space-md)] flex items-center justify-between gap-[var(--space-sm)]"><h2 className="text-xl font-semibold">Workspace navigation</h2><Button buttonRef={closeOverlayRef} ariaLabel="Close mobile workspace navigation" onClick={() => ctx.onAction("EVENT_CLOSE_OVERLAY", "close button")}>Close</Button></div><Sidebar ctx={ctx} activeId={activeScreen.id} mobile={true} /></div></div> : null}
      <ContractAliasMarkers />
      <footer className="border-t border-[var(--border)] bg-[var(--surface)] p-[var(--space-md)] text-xs text-[var(--text-dim)]">Desktop keeps graph details visible; tablet moves details to drawers; mobile uses card-list tables and simplified graph fallbacks. Latest action: <span aria-live="polite">{log}</span></footer>
    </section>
  </main>;
}

function Sidebar({ ctx, activeId, mobile }: { ctx: ComponentContext; activeId: string; mobile: boolean }) { return <nav data-ds-id={mobile ? undefined : "ds:global-shell:sidebar"} aria-label={mobile ? "Mobile PM workspace surfaces" : "PM workspace surfaces"} className={`${mobile ? "" : "border-b border-[var(--border)] bg-[var(--surface)] p-[var(--space-md)] md:border-b-0 md:border-r md:p-[var(--space-lg)]"}`}><p className="font-mono text-xs uppercase tracking-[0.18em] text-[var(--text-dim)]">Responsive surface nav</p><ul className="mt-[var(--space-md)] grid gap-[var(--space-xs)]">{screens.filter((screen) => screen.route !== "embedded").map((screen) => <li key={screen.id}><a href={`#${surfaceAnchors[screen.id] ?? screen.id.replace("screen:", "surface-")}`} onClick={() => { ctx.onAction("EVENT_HASH_NAVIGATE", screen.label); if (mobile) ctx.onAction("EVENT_CLOSE_OVERLAY", "selected navigation target"); }} aria-current={screen.id === activeId ? "page" : undefined} className={`block rounded-[var(--radius)] border border-transparent px-[var(--space-sm)] py-[var(--space-xs)] text-sm text-[var(--text)] hover:border-[var(--border)] hover:bg-[var(--bg)] ${focusRing}`}>{screen.label}</a></li>)}</ul></nav> }
function ContractAliasMarkers() { return <div hidden aria-hidden="true"><span data-state="bulk-action-processing" data-state-alias="bulk_action_processing" data-event="EVENT_SAVE_BULK" />{contractAliases.map((dsId) => <span key={dsId} data-ds-id={dsId} />)}</div> }
function StateControls({ ctx }: { ctx: ComponentContext }) { return <section aria-label="Boundary state controls" className="mt-[var(--space-md)] flex flex-wrap gap-[var(--space-xs)]">{allStates.map((state) => <button key={state} type="button" aria-pressed={ctx.status === state} onClick={() => ctx.setStatus(state)} className={`${chip} ${focusRing} ${ctx.status === state ? "bg-[var(--accent-cyan-dim)] text-[var(--text)]" : "bg-[var(--surface)]"}`}>{state.replace(/_/g, " ")}</button>)}</section> }
function SyncBanner({ ctx, log }: { ctx: ComponentContext; log: string }) { return <aside data-ds-id="ds:global-shell:sync-banner" data-state={ctx.status} role="status" aria-live="polite" className={`${inset} p-[var(--space-sm)] text-xs text-[var(--text-dim)]`}><strong className="text-[var(--text)]">Health: {ctx.status.replace(/_/g, " ")}</strong><p>{log}</p><div className="mt-[var(--space-xs)] flex flex-wrap gap-[var(--space-xs)]"><Button onClick={() => ctx.onAction("EVENT_DISCONNECT", "cached read-only mode")}>Disconnect</Button><Button onClick={() => ctx.onAction("EVENT_RECONNECT", "POST /api/sync/rehydrate")}>Reconnect</Button><Button onClick={() => ctx.onAction("EVENT_KEEP_LOCAL", "POST /api/sync/conflicts/:id/resolve keep local")}>Keep local</Button><Button onClick={() => ctx.onAction("EVENT_USE_SERVER", "POST /api/sync/conflicts/:id/resolve use server")}>Use server</Button></div></aside> }
function ScreenShell({ screen, featured, ctx }: { screen: Screen; featured: boolean; ctx: ComponentContext }) { const anchor = surfaceAnchors[screen.id] ?? screen.id.replace("screen:", "surface-"); const state = screen.states.includes(ctx.status) ? ctx.status : (shellStates.includes(ctx.status) ? ctx.status : "default"); const layoutClass = screen.id === "screen:rtm-dashboard" ? "lg:grid-cols-2 xl:grid-cols-[1fr_1fr_1fr]" : screen.id === "screen:task-list" ? "lg:grid-cols-[18rem_minmax(0,1fr)]" : screen.id === "screen:trace-explorer" ? "lg:grid-cols-[minmax(0,1.5fr)_minmax(18rem,0.7fr)]" : screen.id === "screen:approval-gates" ? "lg:grid-cols-[minmax(14rem,0.8fr)_minmax(0,1.2fr)_minmax(14rem,0.8fr)]" : "lg:grid-cols-2 xl:grid-cols-3"; return <section id={anchor} data-screen-id={screen.id} data-ds-id={screen.dsId} data-state={state} className={`${panel} ${motion} scroll-mt-[var(--space-lg)] p-[var(--space-md)] ${featured ? "ring-2 ring-[var(--border-highlight)]" : ""}`} aria-labelledby={`${screen.id}-title`}><header className="grid gap-[var(--space-sm)] border-b border-[var(--border)] pb-[var(--space-md)] lg:grid-cols-[minmax(0,1fr)_auto] lg:items-start"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-[var(--text-dim)]">{screen.route}</p><h3 id={`${screen.id}-title`} className="mt-[var(--space-xs)] text-xl font-semibold">{screen.label}</h3><p className="mt-[var(--space-xs)] text-sm text-[var(--text-dim)]">{screen.layout}</p></div><StateList states={screen.states} /></header><BoundaryNotice state={state} ctx={ctx} /><section data-ds-id={screen.rootDsId} aria-label={`${screen.label} layout regions`} className={`mt-[var(--space-md)] grid gap-[var(--space-md)] ${layoutClass}`}>{screen.regions.map((item) => <RegionSlot key={item.dsId} region={item} ctx={ctx} state={state} />)}</section><aside aria-label={`${screen.label} routing and API contract`} className="mt-[var(--space-md)] grid gap-[var(--space-sm)] lg:grid-cols-2"><section className={`${inset} p-[var(--space-sm)]`}><h4 className="font-mono text-xs uppercase text-[var(--text-dim)]">Anchors and states</h4><p className="mt-[var(--space-xs)] text-xs text-[var(--text-dim)]">{screen.anchors?.join(" / ") || "primary route"}</p></section><section className={`${inset} p-[var(--space-sm)]`}><h4 className="font-mono text-xs uppercase text-[var(--text-dim)]">Go REST data flow</h4>{screen.endpoints.map((endpoint) => <p key={endpoint} className="font-mono text-[0.7rem] text-[var(--text)]">{endpoint}</p>)}</section></aside></section> }
function BoundaryNotice({ state, ctx }: { state: ViewState; ctx: ComponentContext }) { if (state === "default") return null; const copy: Record<ViewState, string> = { default: "", loading: "Loading route data with layout-matched skeletons.", empty: "No matching records yet; clear filters or refresh from the API.", error: "The API request failed; retry keeps the current shell route safe.", offline: "Offline read-only cache is active and eligible writes are queued.", forbidden: "You do not have permission for this data; return to the workspace shell.", partial: "Trace graph is available while enrichment continues through REST endpoints.", saving: "Saving through the API; edited controls are temporarily disabled.", pending: "Human confirmation is pending before this API-backed workflow can continue.", success: "API update succeeded and the shell can refresh without losing route context.", rehydrating: "Connectivity returned; queued edits are rehydrating before conflict checks complete.", not_found: "The requested task or storyboard was not found; open the parent list.", sync_conflict: "Rehydration found a queued edit conflict; choose local or server version.", bulk_action_processing: "Bulk action processing is running through PUT /api/tasks/bulk; task selection controls stay locked until the batch resolves.", insufficient_evidence: "Approval is blocked until required evidence or an audit reason is supplied.", decision_submitted: "Decision submitted and audit receipt recorded." }; return <aside role="status" aria-live="polite" className={`${inset} mt-[var(--space-md)] p-[var(--space-sm)] text-sm text-[var(--text)]`}><strong className="capitalize">{state.replace(/_/g, " ")}</strong><p className="text-[var(--text-dim)]">{copy[state]}</p><div className="mt-[var(--space-xs)] flex flex-wrap gap-[var(--space-xs)]"><Button onClick={() => ctx.onAction(state === "forbidden" || state === "not_found" ? "EVENT_BACK" : "EVENT_RETRY", copy[state])}>{state === "forbidden" || state === "not_found" ? "Back to safe route" : state === "success" ? "Refresh route" : "Retry"}</Button>{state === "sync_conflict" ? <><Button onClick={() => ctx.onAction("EVENT_KEEP_LOCAL", "resolve conflict with local edit")}>Keep local</Button><Button onClick={() => ctx.onAction("EVENT_USE_SERVER", "resolve conflict with server version")}>Use server</Button></> : null}</div></aside> }
function RegionSlot({ region, ctx, state }: { region: Region; ctx: ComponentContext; state: ViewState }) { return <article data-ds-id={region.dsId} data-state={region.type === "BulkActionBar" && state === "bulk_action_processing" ? "bulk_action_processing" : state} aria-busy={state === "loading" || state === "saving" || state === "bulk_action_processing" || state === "pending" || state === "rehydrating"} className={`${inset} ${motion} min-h-32 p-[var(--space-md)]`}><header><p className="font-mono text-xs uppercase tracking-[0.14em] text-[var(--text-dim)]">{region.type}</p><h4 className="mt-[var(--space-xs)] text-sm font-semibold text-[var(--text)]">{titleFor(region.type)}</h4></header><div className="mt-[var(--space-sm)] text-sm text-[var(--text)]"><RegionContent region={region} ctx={ctx} state={state} /></div>{region.actions ? <p className="mt-[var(--space-sm)] font-mono text-[0.68rem] text-[var(--text-dim)]">Actions: {region.actions}</p> : null}</article> }
function RegionContent({ region, ctx, state }: { region: Region; ctx: ComponentContext; state: ViewState }) { if (state === "loading" || state === "rehydrating") return <Skeleton variant={region.type} />; if (state === "empty") return <EmptyState ctx={ctx} />; if (state === "error") return <ErrorState ctx={ctx} />; if (state === "forbidden") return <ForbiddenState ctx={ctx} />; if (state === "offline") return <p>Cached read-only content remains visible. Submit controls explain queued API recovery instead of direct DB or shell access.</p>; if (state === "not_found") return <List items={["Missing entity id: bd-missing", "Parent list remains available", "Trace link can be retried after API reindex"]} action={() => ctx.onAction("EVENT_BACK", "open parent route")} />; if (state === "sync_conflict") return <List items={["Local queued owner: Mina Rourke", "Server owner: Linh Okafor", "Audit trail will record resolution"]} />; if (state === "insufficient_evidence") return <p role="alert">Field-level validation: audit reason must describe missing evidence before approval is enabled.</p>; if (state === "decision_submitted" || state === "success") return <p>Audit receipt saved through POST /api/approval/:id/decision and the queue can refresh.</p>; if (state === "bulk_action_processing") return <p aria-live="polite">Bulk action processing via PUT /api/tasks/bulk. Selection, priority, and owner controls are disabled until the batch completes or retry recovers.</p>; if (state === "saving" || state === "pending") return <p aria-live="polite">Saving via REST endpoint. Controls with pending writes are disabled until success or rollback.</p>; if (state === "partial") return <p>Partial enrichment: cached graph nodes render now while GitHub, FastCode, and CI summaries hydrate from the backend API.</p>; switch (region.type) {
  case "KpiCards": return <div className="grid gap-[var(--space-sm)] sm:grid-cols-2">{metrics.map((m) => <Metric key={m.k} {...m} />)}</div>;
  case "CoverageHeatmap": return <div className="grid grid-cols-4 gap-1">{["br-prd04-s1", "s4", "s8", "s10.3a", "s12", "s15", "s18", "s18a"].map((id, i) => <button key={id} aria-label={`Open trace for ${id}`} onClick={() => ctx.onAction("EVENT_VIEW_TRACE", `/trace/${id}`)} className={`${focusRing} rounded-[var(--radius)] border border-[var(--border)] p-2 text-left font-mono text-[0.65rem] ${i === 1 ? "bg-[var(--surface-elevated)]" : "bg-[var(--surface)]"}`}>{id}<span className="block text-[var(--text-dim)]">{[94, 67, 88, 73, 91, 84, 79, 62][i]}%</span></button>)}</div>;
  case "TaskProgressPanel": return <List items={tasks.map((t) => `${t.id} · ${t.status} · ${t.cov}`)} action={(item) => ctx.onAction("EVENT_VIEW_TASK", item)} />;
  case "KnowledgeGraphWidget": case "MiniGraphWidget": case "MiniGraphCanvas": case "GraphCanvas": return <Graph ctx={ctx} />;
  case "GapAnalysisList": return <List items={["Missing approval evidence for br-prd04-s10.3a", "Coverage below target on trace explorer mobile", "Policy copy absent for forbidden portfolio budget"]} action={(item) => ctx.onAction("EVENT_REFRESH", item)} />;
  case "BoardSelector": case "ScenarioTabs": case "ScenarioSelector": case "TypeFilters": case "ComponentSectionNav": case "TaskTabs": return <Tabs ctx={ctx} values={region.type === "TaskTabs" ? ["detail", "activity", "graph", "code", "approval"] : ["sprint", "release", "bug-triage", "trace"]} />;
  case "KanbanColumns": return <div className="grid gap-2 md:grid-cols-3">{["Ready", "In progress", "Review"].map((c, i) => <section key={c} className={`${inset} p-2`}><b>{c}</b><button onClick={() => ctx.onAction("EVENT_MOVE_CARD", `${tasks[i].id} to ${c}`)} className={`mt-2 block w-full rounded-[var(--radius)] bg-[var(--surface)] p-2 text-left ${focusRing}`}>{tasks[i].title}</button></section>)}</div>;
  case "TaskTable": return <table className="w-full text-left text-xs"><thead><tr>{["Bead", "Owner", "Priority", "Coverage"].map((h) => <th key={h} className="border-b border-[var(--border)] p-2"><button aria-label={`Sort by ${h}`} onClick={() => ctx.onAction("EVENT_HASH_NAVIGATE", `sort ${h}`)} className={focusRing}>{h}</button></th>)}</tr></thead><tbody>{tasks.map((t) => <tr key={t.id}><td className="p-2"><button onClick={() => ctx.onAction("EVENT_VIEW_TASK", `/tasks/${t.id}`)} className={focusRing}>{t.id}</button></td><td>{t.owner}</td><td>{t.prio}</td><td>{t.cov}</td></tr>)}</tbody></table>;
  case "EditableFieldGroup": return <form onSubmit={(e) => { e.preventDefault(); ctx.onAction("EVENT_SAVE_TASK", `PUT /api/tasks/bd-webui-shell owner=${ctx.taskOwner} priority=${ctx.taskPriority}`) }} aria-describedby="task-save-status task-owner-error" className="grid gap-2"><label>Assignee<input value={ctx.taskOwner} disabled={isWriteLocked(ctx.status)} aria-invalid={!ctx.taskOwner.trim()} aria-describedby="task-owner-error" onChange={(e) => ctx.setTaskOwner(e.target.value)} className={`${inset} mt-1 w-full p-2 disabled:opacity-60 ${focusRing}`} /></label>{!ctx.taskOwner.trim() ? <p id="task-owner-error" role="alert" className="text-[var(--accent-amber)]">Choose an assignee before saving the task.</p> : <p id="task-owner-error" className="text-xs text-[var(--text-dim)]">Assignee is ready for REST save.</p>}<label>Priority<select value={ctx.taskPriority} disabled={isWriteLocked(ctx.status)} onChange={(e) => ctx.setTaskPriority(e.target.value)} className={`${inset} mt-1 w-full p-2 disabled:opacity-60 ${focusRing}`}><option>P0</option><option>P1</option><option>P2</option></select></label><p id="task-save-status" className="text-xs text-[var(--text-dim)]">Saving, offline, and forbidden states lock field edits and expose retry or safe-return recovery.</p><Button disabled={isWriteLocked(ctx.status) || !ctx.taskOwner.trim()}>Save task</Button></form>;
  case "DecisionControls": return <form onSubmit={(e) => { e.preventDefault(); ctx.onAction("EVENT_APPROVAL_DECISION", `POST /api/approval/bd-webui-shell/decision reason=${ctx.approvalReason}`) }} className="grid gap-2"><label>Audit reason<textarea aria-describedby="approval-reason-error" aria-invalid={ctx.approvalReason.length < 25} value={ctx.approvalReason} disabled={isWriteLocked(ctx.status)} onChange={(e) => ctx.setApprovalReason(e.target.value)} className={`${inset} mt-1 min-h-20 w-full p-2 disabled:opacity-60 ${focusRing}`} /></label>{ctx.approvalReason.length < 25 ? <p id="approval-reason-error" role="alert" className="text-[var(--accent-amber)]">Add a specific evidence reason before approving.</p> : <p id="approval-reason-error" className="text-xs text-[var(--text-dim)]">Evidence reason is specific enough for audited approval.</p>}<div className="flex flex-wrap gap-2"><Button disabled={isWriteLocked(ctx.status) || ctx.approvalReason.length < 25}>Approve</Button><Button disabled={isWriteLocked(ctx.status)} onClick={() => ctx.onAction("EVENT_APPROVAL_DECISION", "request changes")}>Request changes</Button></div></form>;
  case "ConfidenceVote": return <form onSubmit={(e) => { e.preventDefault(); ctx.onAction("EVENT_CONFIDENCE_VOTE", `POST /api/pi/confidence-vote value=${ctx.vote}`) }} className="grid gap-2"><label>Confidence 1 to 5<input type="range" min="1" max="5" value={ctx.vote} disabled={isWriteLocked(ctx.status)} onChange={(e) => ctx.setVote(e.target.value)} className="w-full" /></label><p className="font-mono">Current vote: {ctx.vote}</p><Button disabled={isWriteLocked(ctx.status)}>Submit vote</Button></form>;
  case "SearchInput": return <form onSubmit={(e) => { e.preventDefault(); ctx.onAction("EVENT_SEARCH", ctx.query) }} className="grid gap-2"><input aria-label="Explorer search query" value={ctx.query} onChange={(e) => ctx.setQuery(e.target.value)} className={`${inset} p-2 ${focusRing}`} /><Button>Run explorer search</Button></form>;
  case "TerminalMosaic": case "TerminalLineList": return <pre className={`${inset} overflow-auto p-3 font-mono text-[0.68rem] text-[var(--text-dim)]`}>GET /api/ci/runs returned read-only stream{"\n"}browser command execution: forbidden{"\n"}agent event bd-webui-shell passed checks</pre>;
  case "PortfolioTable": return <List items={["Epic br-prd04-s8 route parity · budget hidden for viewers", "Epic br-prd04-s5 graph traversal · 72.8% delivered", "Epic br-prd04-s12 approval gates · forecast Q2 2026"]} action={(item) => ctx.onAction("EVENT_VIEW_TASK", item)} />;
  case "DocTree": return <List items={docs} action={(item) => ctx.onAction("EVENT_VIEW_DOC", item)} />;
  case "RenderedDocument": return <p>Section <button onClick={() => ctx.onAction("EVENT_VIEW_TRACE", "/trace/br-prd04-s8")} className={focusRing}>br-prd04-s8</button> maps showcase routes to Core WebUI routes with REST-only data boundaries.</p>;
  case "UsecaseFlow": case "StepTimeline": return <ol className="grid gap-2">{storySteps.map((s, i) => <li key={s} className="border-l border-[var(--border)] pl-3"><span className="font-mono text-[var(--text-dim)]">0{i + 1}</span> {s}</li>)}</ol>;
  default: return <DefaultRegion region={region} ctx={ctx} />;
} }
function Skeleton({ variant }: { variant?: string }) { const graph = variant?.includes("Graph") || variant?.includes("Canvas"); return <div aria-label={`${variant ?? "region"} loading skeleton`} className="grid gap-[var(--space-sm)]"><div className="h-4 w-2/3 rounded-[var(--radius)] bg-[var(--surface-elevated)]" /><div className={`${graph ? "h-36" : "h-20"} rounded-[var(--radius)] bg-[var(--surface-elevated)]`} /><div className="grid grid-cols-3 gap-[var(--space-sm)]"><span className="h-8 rounded-[var(--radius)] bg-[var(--surface-elevated)]" /><span className="h-8 rounded-[var(--radius)] bg-[var(--surface-elevated)]" /><span className="h-8 rounded-[var(--radius)] bg-[var(--surface-elevated)]" /></div></div> }
function EmptyState({ ctx }: { ctx: ComponentContext }) { return <div><p>No API records match this route or filter. Clear search, create upstream evidence, or refresh current route data.</p><Button onClick={() => ctx.onAction("EVENT_REFRESH", "empty state recovery")}>Refresh data</Button></div> }
function ErrorState({ ctx }: { ctx: ComponentContext }) { return <div><p>Request failed at the Go REST boundary. Existing shell state remains safe.</p><Button onClick={() => ctx.onAction("EVENT_RETRY", "retry API load")}>Retry load</Button></div> }
function ForbiddenState({ ctx }: { ctx: ComponentContext }) { return <div><p>Permission is missing for this route. Sensitive budget and approval data remain hidden.</p><Button onClick={() => ctx.onAction("EVENT_BACK", "return from forbidden state")}>Back to workspace</Button></div> }
function DefaultRegion({ region, ctx }: { region: Region; ctx: ComponentContext }) { const copy: Record<string, string[]> = { TaskFilters: ["Status: open", "Priority: P0/P1", "Assignee: release train"], BulkActionBar: ["3 selected", "State: bulk_action_processing", "Save through PUT /api/tasks/bulk"], BoardStats: ["WIP 7 of 9", "Cycle 3.7 days", "Blocked 2"], RteEscalationBadge: ["Escalation: bd-rtm-graph", "Owner: RTE Pod Copper"], ApprovalQueue: ["bd-webui-shell pending", "bd-rtm-graph evidence needed"], EvidenceHub: ["PRD link verified", "Plan link verified", "Commit trailer verified"], RtmMatrix: ["PRD to Plan", "Plan to Task", "Task to Commit"], SectionCoverageBadges: ["covered", "partial", "gap"], TraceToolbar: ["Depth full", "Preset sprint", "Partial enrichment visible"], TraversalLayers: ["PRD", "Plan", "Task", "Commit"], DetailPanel: ["Selected br-prd04-s8", "Impact 14 tasks"], GroupedResults: ["Task bd-webui-shell", "Doc PRD-04", "Commit 16cb87e"], Roadmap: ["Q1 contract", "Q2 workspace", "Q3 governance"], StrategicSandbox: ["Capacity 84.6%", "Save plan"], BusinessValueScoring: ["Risk 7", "Value 9", "Time criticality 6"], RoamBoard: ["Resolved 4", "Owned 5", "Mitigated 3"], GitGraphCanvas: ["main", "feature/webui", "release/train-04"], CommitDetail: ["16cb87e", "Beads-ID: br-prd04-s8"], FileLeasePanel: ["apps/website page locked by PM", "docs/design free"], ActivityFeed: ["Mina moved bd-webui-shell", "Oren linked br-prd04-s8"], SprintDayTimeline: ["09:17 standup", "11:42 gate review"], ComponentExamples: ["Button", "Badge", "Data table", "Error banner"], JourneyFilter: ["Role PM", "Module approval", "Outcome audited"], GuidancePanel: ["Mechanism: API-backed navigation", "Action: verify state label", "Investigating: coverage gaps"], StoryboardRolePanel: ["QA", "Validates E2E metadata"], RelatedUsecases: ["core-navigate-task", "approval-approve", "offline-rehydrate-conflict"], NodeDetailPanel: ["Open full trace", "Selected bead bd-webui-shell"] }; const items = copy[region.type] ?? ["REST payload normalized", "Boundary states labeled", "Traceable ds_id present"]; return <List items={items} action={region.actions ? (item) => ctx.onAction(region.actions!.split(",")[0].trim() as EventName, item) : undefined} /> }
function Graph({ ctx }: { ctx: ComponentContext }) { return <div className="grid gap-2"><div className="relative h-36 rounded-[var(--radius)] border border-[var(--border)] bg-[var(--surface)]"><button aria-label="Open PRD trace node" onClick={() => ctx.onAction("EVENT_VIEW_TRACE", "/trace/br-prd04-s8")} className={`absolute left-[12%] top-[20%] ${chip} ${focusRing}`}>PRD</button><button aria-label="Open task graph node" onClick={() => ctx.onAction("EVENT_VIEW_TASK", "/tasks/bd-webui-shell")} className={`absolute left-[48%] top-[48%] ${chip} ${focusRing}`}>Task</button><button aria-label="Open document graph node" onClick={() => ctx.onAction("EVENT_VIEW_DOC", "/docs/br-prd04")} className={`absolute right-[8%] top-[18%] ${chip} ${focusRing}`}>Doc</button></div><p className="text-xs text-[var(--text-dim)]">Partial enrichment falls back to cached graph while GitHub and CI details hydrate through REST.</p></div> }
function Tabs({ ctx, values }: { ctx: ComponentContext; values: string[] }) { return <div className="flex flex-wrap gap-2">{values.map((v) => <button key={v} onClick={() => ctx.onAction("EVENT_HASH_NAVIGATE", `#${v}`)} className={`${chip} ${focusRing} bg-[var(--surface)]`}>{v}</button>)}</div> }
function List({ items, action }: { items: string[]; action?: (item: string) => void }) { return <ul className="grid gap-2">{items.map((item) => <li key={item} className="flex items-start justify-between gap-2 border-b border-[var(--border)] pb-2 last:border-b-0"><span>{item}</span>{action ? <button onClick={() => action(item)} className={`${chip} ${focusRing}`}>Open</button> : null}</li>)}</ul> }
function Metric({ k, v, d }: { k: string; v: string; d: string }) { return <section className="border-l border-[var(--border)] pl-3"><p className="text-xs text-[var(--text-dim)]">{k}</p><p className="font-mono text-2xl text-[var(--text)]">{v}</p><p className="text-[0.68rem] text-[var(--text-dim)]">{d}</p></section> }
function Button({ children, onClick, disabled, ariaLabel, buttonRef }: { children: ReactNode; onClick?: () => void; disabled?: boolean; ariaLabel?: string; buttonRef?: Ref<HTMLButtonElement> }) { return <button ref={buttonRef} type={onClick ? "button" : "submit"} onClick={onClick} disabled={disabled} aria-label={ariaLabel} className={`${chip} ${motion} ${focusRing} bg-[var(--surface)] text-[var(--text)] active:translate-y-px disabled:cursor-not-allowed disabled:opacity-60`}>{children}</button> }
function titleFor(type: string) { return type.replace(/([a-z])([A-Z])/g, "$1 $2") }
function StateList({ states }: { states: ViewState[] }) { return <ul className="flex max-w-md flex-wrap gap-[var(--space-xs)]" aria-label="Declared boundary states">{states.map((state) => <li key={state} data-state={state} className={chip}>{state.replace(/_/g, " ")}</li>)}</ul> }
function isWriteLocked(state: ViewState) { return ["saving", "bulk_action_processing", "pending", "rehydrating", "offline", "forbidden"].includes(state) }

export { shellStates };
